#!/bin/bash

#$ -V -cwd
#$ -l h_rt=50:00:00
#$ -l h_vmem=10G
#$ -t 1-145
#$ -tc 145

###############################################################################
# Script: 02_extract_peak_mafs.sh
#
# Purpose:
#   Extract MAF alignments corresponding to each ATAC peak.
#
# Workflow:
#   Output files generated by:
#       01_prepare_peak_subsets.sh
#
#   are used as input here.
#
# Input:
#   *_subset_extracted_peaks??
#
# MAF files:
#   ssa<CHR>_AB.maf
#
# Output:
#   ssa<CHR>/
#   ├── ssa1_1000_1500.maf
#   ├── ssa1_2000_2500.maf
#   └── ...
#
# One MAF file is generated per ATAC peak.
#
# Install mafTools to extract MAF files
#
###############################################################################

set -euo pipefail

# Retrieve the chunk corresponding to this array task
INPUT_FILE=$(ls *_subset_extracted_peaks?? | sed -n "${SGE_TASK_ID}p")

PREFIX=$(basename "${INPUT_FILE}")
CHR=${PREFIX%%_subset_extracted_peaks*}

echo "Input chunk: ${INPUT_FILE}"
echo "Chromosome : ${CHR}"

while read -r chrom start end; do

    maf_file="ssa${chrom}_AB.maf"

    output_file="ssa${CHR}/ssa${chrom}_${start}_${end}.maf"

    softwares/mafTools/bin/mafExtractor \
        -m "${maf_file}" \
        -s "Ssal_A.${chrom}" \
        --start "${start}" \
        --stop "${end}" \
        > "${output_file}"

done < "${INPUT_FILE}"

echo "Finished ${INPUT_FILE}"