###############################################################################
# Script: 03_overlay_maf_with_atac.R
#
# Purpose:
#   Identify conserved ATAC peaks between Atlantic salmon and rainbow trout
#   using multi-species MAF alignments.
#
# Workflow:
#
#   MAF files generated by:
#       01_prepare_peak_subsets.sh
#       02_extract_peak_mafs.sh
#
#   For each MAF alignment:
#       1. Parse alignment blocks
#       2. Recover genomic coordinates
#       3. Overlay with ATAC peaks
#       4. Remove ambiguous peak mappings
#       5. Summarize conservation patterns
#
# Outputs:
#   *_salmon_trout_atac_maf_final.xlsx
#   *_salmon_trout_atac_maf_final.txt
#   *_peak_combination.xlsx
#   *_sequence_combination.xlsx
#
###############################################################################

###############################################################################
# Load required packages
###############################################################################

library(tidyverse)
library(fuzzyjoin)
library(openxlsx)
library(tidygenomics)

message("Required libraries loaded")

###############################################################################
# Read chromosome identifier supplied from job array
###############################################################################

args <- commandArgs(trailingOnly = TRUE)

if(length(args) == 0){
  stop("Chromosome identifier not supplied")
}

chr <- args[1]

###############################################################################
# Set chromosome-specific working directory
###############################################################################

setwd(file.path("aquafaang_atac",
                "peaks_maf_files",
                chr))

##create directory to store the outputs
dir.create(paste("../",chr,"_atac_maf_results", sep=""), showWarnings = FALSE)
message("directory created")

##### read key datasets
reshaped_salmon_trout_atac <- read.table("./reshaped_salmon_trout_atac_peaks_2024.txt",header = T)
salmon_ATAC <- "./salmon_3_fields_consensus_2024.txt"
trout_ATAC<- "./trout_3_fields_consensus_2024.txt"
pike_CNE<-"./CNEs_pike_2023.03.23_coordinates.txt"

##set Rdat file name to save data for each run
Rdata <- paste(chr,"_atac_maf_overlay.RData",sep="") 

##### curate atac data from both species and merge it into a single datasheet
##salmon
ssal_atac_peaks<-read.table(paste(salmon_ATAC,sep=""), col.names = c("chromosome","start","end"))
ssal_atac_peaks$chromosome <- as.numeric(as.character(ssal_atac_peaks$chromosome))
ssal_atac_peaks$chromosome <- sprintf("%02d",ssal_atac_peaks$chromosome)
ssal_atac_peaks$chromosome = paste0("Ssal",ssal_atac_peaks$chromosome)

##trout
trout_atac_peaksa<-read.table(paste(trout_ATAC, sep=""), col.names = c("chromosome","start","end"))
trout_atac_peaksa$chromosome <- as.numeric(as.character(trout_atac_peaksa$chromosome)) ##THIS REMOVES CHR Y GET IT BACK
trout_atac_peaksa<-trout_atac_peaksa %>% filter(!is.na(chromosome))
trout_atac_peaksa$chromosome <- sprintf("%02d",trout_atac_peaksa$chromosome)

trout_atac_peaksb<-read.table(paste(trout_ATAC, sep=""), col.names = c("chromosome","start","end"))
chr_y_trout<-trout_atac_peaksb %>% filter(chromosome=="Y")

trout_atac_peaks <- bind_rows(trout_atac_peaksa,chr_y_trout)
trout_atac_peaks$chromosome = paste0("Omyk",trout_atac_peaks$chromosome)

##merge 
merged_atac_peaks<-bind_rows(ssal_atac_peaks,trout_atac_peaks) %>% mutate_at(vars("start","end"),as.integer)
message("all key datasets read")

###############################################################################
# Function: MAF2tbl
#
# Converts a MAF alignment file into a tabular representation.
#
# Returns:
#   One row per aligned sequence block.
###############################################################################

MAF2tbl <- function(mafFile){
  x <- readLines(mafFile)
  
  aLines <- grepl("^a",x)
  sLines <- grepl("^s",x)
  
  tibble(idx=cumsum(aLines),txt=x) %>% 
    filter(sLines) %>%
    separate(txt, into=c("s","src","start","size","strand","srcSize","text"),sep = "[ \t]+") %>% 
    select(-s) %>% 
    mutate_at(vars(start,size,srcSize),as.integer) 
}

##########################################
# read maf files using the function above
##########################################

Files <- list.files(pattern = "*.maf",full.names = TRUE)
maf_list <- lapply(Files,MAF2tbl) ### convert all maf files to tables
names(maf_list) <- Files
message("maffiles read into table")

###############################################################################
# Function: curate_maf
#
# For each extracted MAF alignment:
#
# 1. Convert alignment coordinates into genomic coordinates.
# 2. Cluster nearby alignment fragments.
# 3. Merge fragmented alignments.
# 4. Retain the largest alignment block per species.
#
# This step removes fragmented alignments and identifies the
# primary orthologous interval represented by the MAF file.
###############################################################################

curate_maf<- function(maftable){
  maftable %>% 
    select(c("src","start","size","strand","srcSize"))  %>%
    separate(src, into=c("species", "chromosome"), sep="\\.") %>% 
    mutate(end= ifelse(strand=="+", start+size,
                       ifelse(strand=="-",start+size,0))) %>% 
    mutate(pos_start=ifelse(strand=="+",start, 
                            ifelse(strand=="-",srcSize - end,0))) %>%
    mutate (pos_end=ifelse(strand=="+",end,
                           ifelse(strand=="-",srcSize - start,0))) %>%
    select(c("species","chromosome","strand","pos_start","pos_end","size")) %>%
    filter(size>10) %>%
    genome_cluster(.,by = c("chromosome", "pos_start", "pos_end"),max_distance=1000) %>%
    group_by(species,chromosome,cluster_id) %>%
    summarise(start = min(pos_start, na.rm=TRUE),end = max(pos_end, na.rm=TRUE), size = sum(size)) %>%
    ungroup %>%
    mutate(range = end-start) %>%
    group_by(species,chromosome) %>% top_n(1, size)%>% ungroup %>%
    group_by(species) %>% top_n(1, size) %>% ungroup 
  # Retain the largest alignment block for each species.
  # This removes smaller fragmented alignments and focuses
  # downstream analyses on the primary orthologous region.
}

############################
#run the curate maf function
############################

curated_maf<-lapply(maf_list,curate_maf)
message("maffiles curated")

maf_intervals <- bind_rows(curated_maf, .id = "Origin") %>%
  mutate(Origin = basename(Origin))
message("all maf files curated and combined")

###############################################################################
# Overlay MAF-derived orthologous intervals with ATAC peaks
#
# For each aligned sequence:
#   - Identify overlapping ATAC peaks
#   - Calculate overlap length
#   - Append developmental accessibility profiles
###############################################################################

maf_atac_overlap<-maf_intervals%>%
  filter(!grepl("Eluc*", species)) %>% 
  group_by(Origin) %>%
  mutate_at(vars("chromosome","start","end"),as.integer) %>%
  mutate(chromosome=sprintf("%02d",chromosome)) %>%
  mutate_at(vars("chromosome"),as.character) %>%
  mutate(chromosome=ifelse(grepl("Omyk*", species),paste0("Omyk",chromosome),paste0("Ssal",chromosome))) %>%
  mutate(prop=size/max(size)) %>%
  mutate(chromosome = str_replace(chromosome, "OmykNA", "OmykY")) %>% 
  genome_left_join(merged_atac_peaks, by = (c("chromosome","start","end"))) %>%
  mutate(overlap = pmin(end.x,end.y)- pmax(start.x,start.y)) %>% #overlap values
  mutate(peak_size = end.y - start.y) %>%
  unite(col=region,chromosome.y,start.y,end.y, sep="_",remove = FALSE) %>%
  left_join(reshaped_salmon_trout_atac, by="region") %>% select(-c(cluster_id,region)) %>%
  ungroup

write.xlsx(maf_atac_overlap,paste("../",chr,"_atac_maf_results/",chr,"_salmon_trout_atac_maf_raw.xlsx",sep=""))
message("maffiles overlayed with atac and written to excel file")

###############################################################################
# Remove ambiguous mappings
#
# Regions where a single MAF interval overlaps multiple ATAC peaks
# are removed from downstream analyses.
#
# This ensures that each conserved sequence is associated with a
# single regulatory element.
###############################################################################

ambiguous_peak_regions<-maf_atac_overlap %>% group_by(Origin,chromosome.x) %>% ##highlight regions with multiple peaks under one peak
  summarise(ov_peaks=length(chromosome.x)) %>% 
  ungroup %>% group_by(Origin) %>%
  summarise(ov_peak_max = max(ov_peaks)) %>% ungroup

atac_maf_final<-maf_atac_overlap %>% 
  left_join(ambiguous_peak_regions, by = (c("Origin"))) %>%
  filter(!(ov_peak_max>=2)) %>%
  mutate(Species_order=ifelse(species=="Ssal_A",1,
                              ifelse(species=="Omyk_A",2,
                                     ifelse(species=="Ssal_B",3,
                                            ifelse(species=="Omyk_B",4, "none"))))) %>%
  mutate_at(vars("Species_order"),as.integer) %>%
  select(-c(ov_peak_max)) %>%
  arrange(Origin,Species_order) %>%
  group_by(Origin) %>%
  mutate(sequence_count=length(Origin)) %>%
  mutate(peak_count=sum(!is.na(chromosome.y))) %>%
  ungroup %>%
  filter(sequence_count<=4)%>%
  mutate(species_b=ifelse(!is.na(chromosome.y),species,NA)) %>%
  select(Origin,Species_order,species,sequence_count,peak_count,chromosome.x,start.x,end.x,size,range,prop,chromosome.y,start.y,end.y,overlap,peak_size,
         lateblastulation,midgastrulation,earlysomitogenesis,midsomitogenesis,latesomitogenesis,everything())


write.xlsx(atac_maf_final,paste("../",chr,"_atac_maf_results/",chr,"_salmon_trout_atac_maf_overlaps_removed.xlsx",sep=""))
message("maffiles overlayed with atac and overlaps cleaned")

#####get peaks and sequence combination
atac_maf_final<-atac_maf_final %>% 
  group_by(Origin) %>% 
###############################################################################
# Generate conservation signatures
#
# peak2sp:
#     Species sharing an ATAC peak
#
# chr2sp:
#     Species sharing aligned sequence
#
# These summaries are used to quantify conservation patterns
# across species and subgenomes.
###############################################################################
  mutate( peak2sp = paste(na.omit(chromosome.y),collapse = ",")) %>% 
  mutate( chr2sp = paste(na.omit(chromosome.x),collapse = ",")) %>%
  mutate( peak2sp_simple = paste(na.omit(species_b),collapse = ",")) %>% 
  mutate( chr2sp_simple = paste(na.omit(species),collapse = ",")) %>%
  ungroup() 

## write peaks as new file
peaks_combination<-atac_maf_final %>% select(Origin,peak2sp) %>% 
  distinct(Origin,.keep_all = TRUE) %>% count(peak2sp,name="counts")%>%
  group_by(test = map_chr(strsplit(peak2sp,","), ~paste(sort(as.character(.x)),collapse = ","))) %>% 
  summarise(peak2sp=peak2sp, count=sum(counts),combs=map_chr(strsplit(as.character(peak2sp),","), ~length(as.character(.x)))) %>% 
  arrange(test) %>% group_by(test) %>% slice(1)%>% ungroup %>% select(-c(test))

write.xlsx(peaks_combination,paste("../",chr,"_atac_maf_results/",chr,"_peaks_combination.xlsx",sep=""))
message("peak combination written")

### write seq as new file
seq_combination<-atac_maf_final %>% select(Origin,chr2sp) %>% 
  distinct(Origin,.keep_all = TRUE) %>% count(chr2sp,name="counts") %>%
  group_by(test = map_chr(strsplit(as.character(chr2sp),","), ~paste(sort(as.character(.x)),collapse = ","))) %>% 
  summarise(chr2sp=chr2sp, count=sum(counts),combs=map_chr(strsplit(as.character(chr2sp),","), ~length(as.character(.x)))) %>% 
  arrange(test) %>% group_by(test) %>% slice(1)%>% ungroup %>% select(-c(test))

write.xlsx(seq_combination,paste("../",chr,"_atac_maf_results/",chr,"_sequence_combination.xlsx",sep=""))
message("sequence combination written")

###write one final sheet with all data
write.xlsx(atac_maf_final,paste("../",chr,"_atac_maf_results/",chr,"_salmon_trout_atac_maf_final.xlsx",sep=""))
write.table(atac_maf_final,paste("../",chr,"_atac_maf_results/",chr,"_salmon_trout_atac_maf_final.txt",sep=""),quote = F,col.names = T,row.names = F)
message("maffiles overlayed with atac and final file written")


###############################################################################
# Pike alignments
#
# Pike (Esox lucius) sequences are extracted from the MAF files
# and written separately for future CNE analyses.
###############################################################################


AllDat_maf_pike <- maf_intervals%>%
  filter(grepl("Eluc*", species)) %>% 
  mutate_at(vars("start","end"),as.integer) %>%
  mutate_at(vars("chromosome"),as.character)

message("Pike data pulled out") 

###run the function on your maf data

write.xlsx(AllDat_maf_pike,paste("../",chr,"_atac_maf_results/",chr,"_pike_sequences.xlsx",sep=""))
message("pike data written")



