#!/usr/bin/env Rscript
# =============================================================================
# 03c_ohnolog_som_figures.R
# -----------------------------------------------------------------------------
# Purpose
#   Bar-chart panels for the C1 ohnolog SOM co-clustering analysis (R1-C6).
#   Emits six paired PDF/PNG figures per map (DevMap + BodyMap):
#     * per-cluster co-clustering rate (AORe vs LORe)        (all + _noconst)
#     * aggregated co-clustering rate by stage or tissue group
#     * per-cluster proportion of LORe genes                 (all + _noconst)
#
# Inputs
#   <data_path>/c1_extended_results.RData   (generated by 03b)
#     Provides `devmap_per_clust`, `bodymap_per_clust` (per-cluster
#     co-clustering tables with n_genes, n_partner_here, pct_coclustered,
#     proxiPhylogeny = {AORe, LORe}) and `devmap_gene_counts`,
#     `bodymap_gene_counts` (per-cluster gene counts with pct_LORe).
#
# Analysis chain
#   03  (run first)  → c1_coclustering_results.RData   (pair-level tables)
#   03b (run second) → c1_extended_results.RData       (gene/cluster tables — used here)
#   03c, 03d, 03e    (this + siblings) read the RData files and emit panels
#   04               stitches panels into supplementary composites
#
# Outputs → <outdir>/panels/
#   C1_{devmap,bodymap}_coclustering_per_cluster[.noconst].{pdf,png}
#   C1_devmap_coclustering_by_stage.{pdf,png}
#   C1_bodymap_coclustering_by_tissue.{pdf,png}
#   C1_{devmap,bodymap}_lore_proportion[.noconst].{pdf,png}
#
# Key choices
#   * P* (SOM unit 9) excluded throughout — it is treated separately in the
#     supplement and is not part of the manuscript's M/B/G/S/P scheme.
#   * The raw SOM unit IDs from kohonen (1..16) do NOT match the manuscript
#     labels (M1..P2, C1..C4); `desired_order` below remaps them.
#   * Constitutive clusters (C1-C4 in DevMap, constitutive_class=TRUE in
#     BodyMap) are dropped in the `_noconst` variants because they dilute
#     the stage/tissue-specific signal; both variants are emitted so the
#     composite figure (04) can draw from the preferred set.
#
# Downstream
#   * 04_composite_figures.R stitches `coclustering_by_{stage,tissue}` and
#     `lore_proportion_noconst` panels into Panel A of the supplementary
#     composite figures.
# =============================================================================

suppressPackageStartupMessages({
  library(tidyverse)
  library(viridis)
  library(ggtext)
})

# --- Global font (Helvetica) ------------------------------------------------
# All ggplot text (axes, legends, annotations) and geom_text/label defaults
# render in Helvetica. Individual theme_bw() calls in the plotting helpers
# below re-supply base_family because they reset the theme completely.
font_family <- "Helvetica"
theme_set(theme_bw(base_size = 11, base_family = font_family))
update_geom_defaults("text",  list(family = font_family))
update_geom_defaults("label", list(family = font_family))

outdir    <- "results/ohnolog/panels"
data_path <- "results/ohnolog/data"

load(file.path(data_path, "c1_extended_results.RData"))

# -----------------------------------------------------------------------------
# Shared palette (identical logic across 03c / 03d / 03e)
#
# The DevMap SOM has 16 units but we only use 15 (P*/unit 9 excluded). The
# manuscript presents clusters in a chronological order (M1..P2, then C1..C4)
# that does NOT correspond to kohonen's raw unit numbering. `desired_order`
# is the sequence of RAW unit IDs that, when read left-to-right, reproduces
# the manuscript order; `inferno_cols` is then assigned left-to-right over
# the 11 non-constitutive clusters with C1-C4 painted grey. `match(1:16, …)`
# inverts this ordering so the palette can be keyed by raw unit ID.
# -----------------------------------------------------------------------------
inferno_cols     <- rev(inferno(12, begin = 0.15, end = 0.9))   # M1=yellow → P2=dark
constitutive_col <- "#becacaff"
final_colors_ssal <- c(inferno_cols, rep(constitutive_col, 4))

# Manuscript order → raw kohonen unit IDs (includes unit 9 = P* as 11th slot)
desired_order      <- c(13, 10, 15, 14, 16, 12, 4, 2, 1, 6, 9, 5, 3, 8, 11, 7)
color_order_for_objects <- match(1:16, desired_order)           # invert: raw ID → palette slot
ordered_palette_salmon_devmap <- final_colors_ssal[color_order_for_objects]

# Palette keyed by raw cluster NUMBER (string "1".."16"); plotting code that
# joins on raw cluster IDs can look colours up directly.
devmap_palette <- setNames(ordered_palette_salmon_devmap, as.character(1:16))

# Cluster orderings used downstream. `_heatmap` drops P* (unit 9) from the
# chronological sequence; `devmap_constitutive` holds the four C1-C4 units.
devmap_cluster_order_heatmap <- c(13, 10, 15, 14, 16, 12, 4, 2, 1, 6, 5)
devmap_constitutive <- c(7, 11, 8, 3)
full_devmap_order   <- c(devmap_cluster_order_heatmap, devmap_constitutive)

devmap_label_map <- c(
  "13"="M1","10"="M2","15"="M3","14"="M4",
  "16"="B1","12"="B2","4"="G1","2"="S1","1"="S2",
  "6"="P1","5"="P2",
  "7"="C1","11"="C2","8"="C3","3"="C4"
)

# Tissue colours (BodyMap)
tissue_cols <- c(
  "Brain"="#dce648ff", "Muscle"="salmon", "Liver"="#8a0000ff",
  "Testes"="forestgreen", "Ovary"="#ffa300ff", "Gill"="red2",
  "Head kidney"="black", "Intestine"="hotpink",
  "Multi"="skyblue", "Constitutive"="#becacaff"
)

# Collapse a BodyMap cluster's compound `class_max` label (e.g. "Brain_Gill",
# "Ova_Matured") into a single dominant tissue category.
# Note: `case_when` is evaluated top-down — the order of clauses encodes
# priority when a label contains multiple tissue tokens. "Multi" is the
# catch-all for genuinely mixed/non-specific clusters.
# Args:  lbl — character vector of BodyMap class_max strings.
# Returns: character vector in `tissue_order`.
simplify_tissue <- function(lbl) {
  case_when(
    grepl("Brain", lbl)        ~ "Brain",
    grepl("Muscle", lbl)       ~ "Muscle",
    grepl("Liver", lbl)        ~ "Liver",
    grepl("Testes", lbl)       ~ "Testes",
    grepl("Ova", lbl)          ~ "Ovary",
    grepl("Gill", lbl)         ~ "Gill",
    grepl("HeadKidney", lbl)   ~ "Head kidney",
    grepl("Intestine", lbl)    ~ "Intestine",
    grepl("Constitutive", lbl) ~ "Constitutive",
    TRUE                        ~ "Multi"
  )
}

tissue_order <- c("Brain","Muscle","Gill","Head kidney",
                   "Intestine","Liver","Testes","Ovary","Constitutive")

redip_cols <- c("AORe" = "#c0392b", "LORe" = "#2980b9")

# Save a ggplot to paired PDF + PNG outputs, routed automatically into
# panels/{pdf|png}/{devmap|bodymap}/{const|noconst}/. The routing keys are
# read from the filename:
#   * "_devmap_" / "_bodymap_" in the name → map subfolder
#   * "_noconst" suffix                    → noconst/ ; otherwise const/
# Call sites can keep passing `file.path(outdir, "C1_...")` as before;
# we strip the directory part with basename() and re-route from there.
# Args:
#   fname_base — path or bare name without extension.
#   p          — ggplot object.
#   w, h       — width/height in inches.
#   dpi        — raster resolution for the PNG only (PDF is vector).
# Returns: invisible NULL (called for its side effect).
save_gg <- function(fname_base, p, w, h, dpi = 300) {
  name    <- basename(fname_base)
  map     <- if (grepl("_bodymap_", name)) "bodymap" else "devmap"
  variant <- if (grepl("_noconst$", name)) "noconst" else "const"
  pdf_dir <- file.path(outdir, "pdf", map, variant)
  png_dir <- file.path(outdir, "png", map, variant)
  dir.create(pdf_dir, showWarnings = FALSE, recursive = TRUE)
  dir.create(png_dir, showWarnings = FALSE, recursive = TRUE)
  # cairo_pdf handles Unicode glyphs (▲ / ▼ / ↑ / ↓) properly; the default
  # pdf() device uses a Type 1 encoding that chokes on them.
  ggsave(file.path(pdf_dir, paste0(name, ".pdf")), p, width = w, height = h,
         device = cairo_pdf)
  ggsave(file.path(png_dir, paste0(name, ".png")), p, width = w, height = h, dpi = dpi)
  cat("  Saved", name, "→", map, "/", variant, "\n")
}

# =============================================================================
# PREPARE DATA
# -----------------------------------------------------------------------------
# For each map we build:
#   * `*_coclust`       — per-cluster co-clustering rates joined to labels.
#   * `*_cluster_cols`  — named palette keyed by the manuscript cluster label,
#                          so geoms can colour-map on factor levels directly.
# For BodyMap the cluster x-axis ordering (facet order) is driven by
# (tissue, cluster) so that clusters within the same tissue are contiguous.
# =============================================================================

# --- DevMap ---
devmap_coclust <- devmap_per_clust$per_cluster %>%
  filter(cluster != 9) %>%                                # drop P*

  mutate(
    label = ifelse(is.na(label), "Constitutive", label),
    cluster_label = devmap_label_map[as.character(cluster)],
    cluster_label = factor(cluster_label,
      levels = devmap_label_map[as.character(full_devmap_order)])
  )

devmap_cluster_cols <- setNames(
  devmap_palette[as.character(full_devmap_order)],
  devmap_label_map[as.character(full_devmap_order)]
)

# --- BodyMap ---
bodymap_coclust <- bodymap_per_clust$per_cluster %>%
  mutate(
    label  = ifelse(is.na(label), "Constitutive", label),
    tissue = simplify_tissue(label),
    tissue = factor(tissue, levels = tissue_order)
  ) %>%
  arrange(tissue, cluster)

bodymap_cluster_order <- bodymap_coclust %>%
  distinct(cluster, tissue) %>% arrange(tissue, cluster) %>% pull(cluster)
bodymap_coclust$cluster <- factor(bodymap_coclust$cluster, levels = bodymap_cluster_order)

bodymap_cluster_tissue <- bodymap_coclust %>% distinct(cluster, tissue)
bodymap_cluster_cols <- setNames(
  tissue_cols[as.character(bodymap_cluster_tissue$tissue)],
  bodymap_cluster_tissue$cluster
)

# =================================================================
# FIGURES
# -----------------------------------------------------------------
# Per-cluster and aggregate co-clustering bars now carry three
# significance layers from 03b's test tables:
#   * class-mean dashed reference lines (AORe red / LORe blue)
#   * asterisks above each bar — cluster rate deviates from its
#     class mean (one-sample proportion test, BH-adjusted)
#   * ▲/▼ appended to the cluster's axis label — the cluster's
#     LORe:AORe ratio deviates from the genome-wide fraction
#     (binomial test, BH-adjusted)
# =================================================================
cat("=== Bar charts ===\n")

arrow_up <- "<span style='color:#111'>▲</span>"
arrow_dn <- "<span style='color:#111'>▼</span>"

# Append ▲/▼ to a label when the ratio test is significant.
decorate_ratio_labels <- function(plain_labels, ratio_tbl,
                                  cluster_to_label_map = NULL) {
  # plain_labels: vector of display strings in axis order.
  # ratio_tbl:    a tests tibble with `cluster`, `sig`, `enrichment`.
  # cluster_to_label_map: named vector cluster_id → label for joining.
  if (!is.null(cluster_to_label_map)) {
    ratio_tbl <- ratio_tbl %>%
      mutate(lookup_label = cluster_to_label_map[as.character(cluster)])
    idx <- match(plain_labels, ratio_tbl$lookup_label)
  } else {
    idx <- match(plain_labels, ratio_tbl$cluster)
  }
  sig       <- ratio_tbl$sig[idx]
  enrich    <- ratio_tbl$enrichment[idx]
  suffix    <- ifelse(is.na(sig) | sig == "", "",
                      ifelse(enrich == "up", arrow_up, arrow_dn))
  paste0(plain_labels, ifelse(suffix == "", "", paste0(" ", suffix)))
}

# --- DevMap per-cluster co-clustering (all) --------------------------------
devmap_bar_sig  <- devmap_bar_tests$tests
devmap_means    <- devmap_bar_tests$class_means
devmap_ratio    <- devmap_ratio_tests$tests

devmap_coclust_plot <- devmap_coclust %>%
  left_join(devmap_bar_sig %>% select(cluster, proxiPhylogeny, sig, direction),
            by = c("cluster", "proxiPhylogeny"))

# Custom axis labels with ▲/▼ markers for the LORe-ratio test. Use
# element_markdown so the arrow HTML renders.
dev_cluster_label_order <- levels(devmap_coclust_plot$cluster_label)
dev_axis_labels <- decorate_ratio_labels(
  dev_cluster_label_order, devmap_ratio,
  cluster_to_label_map = devmap_label_map)

p1 <- ggplot(devmap_coclust_plot, aes(x = cluster_label, y = pct_coclustered,
                                       fill = proxiPhylogeny)) +
  geom_col(position = position_dodge(width = 0.8), width = 0.7) +
  geom_hline(data = devmap_means,
             aes(yintercept = 100 * mean_rate, colour = proxiPhylogeny),
             linetype = "dashed", linewidth = 0.45, show.legend = FALSE) +
  geom_text(aes(label = sig, colour = proxiPhylogeny),
            position = position_dodge(width = 0.8),
            vjust = -1.2, size = 3.3, show.legend = FALSE) +
  geom_text(aes(label = n_genes),
            position = position_dodge(width = 0.8), vjust = -0.3, size = 2.2) +
  scale_fill_manual(values = redip_cols,
                    labels = c("AORe" = "Early", "LORe" = "Late"),
                    name = "Rediploidization") +
  scale_colour_manual(values = redip_cols, guide = "none") +
  scale_x_discrete(labels = setNames(dev_axis_labels, dev_cluster_label_order)) +
  labs(x = "SOM cluster", y = "Co-clustering rate (%)") +
  theme_bw(base_size = 11, base_family = font_family) +
  theme(axis.text.x = element_markdown(angle = 45, hjust = 1),
        panel.grid.major.x = element_blank(),
        legend.position = c(0.85, 0.85))

save_gg(file.path(outdir, "C1_devmap_coclustering_per_cluster"), p1, 10, 5.3)

# --- BodyMap per-cluster co-clustering (all) -------------------------------
bodymap_bar_sig  <- bodymap_bar_tests$tests
bodymap_means    <- bodymap_bar_tests$class_means
bodymap_ratio    <- bodymap_ratio_tests$tests

bodymap_coclust_plot <- bodymap_coclust %>%
  mutate(cluster = as.character(cluster)) %>%
  left_join(bodymap_bar_sig %>%
              mutate(cluster = as.character(cluster)) %>%
              select(cluster, proxiPhylogeny, sig, direction),
            by = c("cluster", "proxiPhylogeny")) %>%
  mutate(cluster = factor(cluster, levels = as.character(bodymap_cluster_order)))

bm_cluster_order  <- levels(bodymap_coclust_plot$cluster)
bm_axis_labels    <- decorate_ratio_labels(
  bm_cluster_order, bodymap_ratio,
  cluster_to_label_map = setNames(as.character(sort(as.numeric(bm_cluster_order))),
                                   as.character(sort(as.numeric(bm_cluster_order)))))

p2 <- ggplot(bodymap_coclust_plot, aes(x = cluster, y = pct_coclustered,
                                        fill = proxiPhylogeny)) +
  geom_col(position = position_dodge(width = 0.8), width = 0.7) +
  geom_hline(data = bodymap_means,
             aes(yintercept = 100 * mean_rate, colour = proxiPhylogeny),
             linetype = "dashed", linewidth = 0.4, show.legend = FALSE) +
  geom_text(aes(label = sig, colour = proxiPhylogeny),
            position = position_dodge(width = 0.8),
            vjust = -0.8, size = 2.6, show.legend = FALSE) +
  scale_fill_manual(values = redip_cols,
                    labels = c("AORe" = "Early", "LORe" = "Late"),
                    name = "Rediploidization") +
  scale_colour_manual(values = redip_cols, guide = "none") +
  scale_x_discrete(labels = setNames(bm_axis_labels, bm_cluster_order)) +
  facet_grid(~ tissue, scales = "free_x", space = "free_x") +
  labs(x = "SOM cluster", y = "Co-clustering rate (%)") +
  theme_bw(base_size = 10, base_family = font_family) +
  theme(axis.text.x = element_markdown(angle = 45, hjust = 1, size = 7),
        strip.text = element_text(size = 7),
        panel.grid.major.x = element_blank(),
        legend.position = "bottom")

save_gg(file.path(outdir, "C1_bodymap_coclustering_per_cluster"), p2, 14, 5)

# --- Aggregate helpers -----------------------------------------------------
# For the by-stage / by-tissue aggregates we need the same pair of tests
# (vs class mean, vs genome-wide LORe fraction) at the aggregate level —
# so we recompute them on the rolled-up totals.
#
# Args:
#   agg_df — tibble with (group_col, proxiPhylogeny, total_genes,
#            total_partner_here, pct).
#   group_col — bare column name (stage_group or tissue).
#
# Returns: (means, sig_bars, sig_ratio).
build_aggregate_sig <- function(agg_df, group_col) {
  gc <- rlang::as_name(rlang::enquo(group_col))
  means <- agg_df %>%
    group_by(proxiPhylogeny) %>%
    summarise(mean_rate = sum(total_partner_here) / sum(total_genes),
              .groups = "drop")
  sig_bars <- agg_df %>%
    left_join(means, by = "proxiPhylogeny") %>%
    rowwise() %>%
    mutate(pval = if (total_genes > 0) {
        suppressWarnings(prop.test(total_partner_here, total_genes,
                                    p = mean_rate)$p.value)
      } else NA_real_) %>%
    ungroup() %>%
    group_by(proxiPhylogeny) %>%
    mutate(padj = p.adjust(pval, method = "BH"),
           sig  = case_when(padj < 0.001 ~ "***",
                            padj < 0.01  ~ "**",
                            padj < 0.05  ~ "*",
                            TRUE         ~ "")) %>%
    ungroup()
  # Ratio test per aggregate group: LORe vs AORe proportion
  ratio_df <- agg_df %>%
    select(all_of(gc), proxiPhylogeny, total_genes) %>%
    pivot_wider(names_from = proxiPhylogeny, values_from = total_genes,
                values_fill = 0) %>%
    mutate(total = AORe + LORe)
  p_lore_global <- sum(ratio_df$LORe) / sum(ratio_df$total)
  sig_ratio <- ratio_df %>%
    rowwise() %>%
    mutate(pval = if (total > 0) {
        suppressWarnings(binom.test(LORe, total, p = p_lore_global)$p.value)
      } else NA_real_) %>%
    ungroup() %>%
    mutate(padj = p.adjust(pval, method = "BH"),
           sig  = case_when(padj < 0.001 ~ "***",
                            padj < 0.01  ~ "**",
                            padj < 0.05  ~ "*",
                            TRUE         ~ ""),
           enrichment = ifelse((LORe / pmax(total, 1)) > p_lore_global,
                                "up", "down"))
  list(means = means, sig_bars = sig_bars, sig_ratio = sig_ratio,
       p_lore = p_lore_global)
}

# --- DevMap aggregated by stage --------------------------------------------
stage_group_map <- c(
  "M1"="Maternal","M2"="Maternal","M3"="Maternal","M4"="Maternal",
  "B1"="Blastulation","B2"="Blastulation","G1"="Gastrulation",
  "S1"="Somitogenesis","S2"="Somitogenesis",
  "P1"="Pharyngula","P2"="Pharyngula",
  "C1"="Constitutive","C2"="Constitutive","C3"="Constitutive","C4"="Constitutive"
)
stage_group_order <- c("Maternal","Blastulation","Gastrulation","Somitogenesis","Pharyngula")

devmap_by_stage <- devmap_coclust %>%
  mutate(stage_group = stage_group_map[as.character(cluster_label)]) %>%
  filter(stage_group != "Constitutive") %>%
  group_by(stage_group, proxiPhylogeny) %>%
  summarise(total_genes = sum(n_genes),
            total_partner_here = sum(n_partner_here), .groups = "drop") %>%
  mutate(pct = round(100 * total_partner_here / total_genes, 1),
         stage_group = factor(stage_group, levels = stage_group_order))

stage_sig <- build_aggregate_sig(devmap_by_stage, stage_group)
devmap_by_stage <- devmap_by_stage %>%
  left_join(stage_sig$sig_bars %>% select(stage_group, proxiPhylogeny, sig),
            by = c("stage_group", "proxiPhylogeny"))
stage_axis_labels <- decorate_ratio_labels(
  as.character(levels(devmap_by_stage$stage_group)),
  stage_sig$sig_ratio %>%
    mutate(cluster = as.character(stage_group)) %>%
    select(cluster, sig, enrichment))

p3 <- ggplot(devmap_by_stage, aes(x = stage_group, y = pct, fill = proxiPhylogeny)) +
  geom_col(position = position_dodge(width = 0.7), width = 0.6) +
  geom_hline(data = stage_sig$means,
             aes(yintercept = 100 * mean_rate, colour = proxiPhylogeny),
             linetype = "dashed", linewidth = 0.45, show.legend = FALSE) +
  geom_text(aes(label = sig, colour = proxiPhylogeny),
            position = position_dodge(width = 0.7),
            vjust = -1.3, size = 3.5, show.legend = FALSE) +
  geom_text(aes(label = paste0("n=", total_genes)),
            position = position_dodge(width = 0.7), vjust = -0.3, size = 2.5) +
  scale_fill_manual(values = redip_cols,
                    labels = c("AORe" = "Early", "LORe" = "Late"),
                    name = "Rediploidization") +
  scale_colour_manual(values = redip_cols, guide = "none") +
  scale_x_discrete(labels = setNames(stage_axis_labels,
                                      levels(devmap_by_stage$stage_group))) +
  labs(x = "Developmental stage group", y = "Co-clustering rate (%)") +
  theme_bw(base_size = 11, base_family = font_family) +
  theme(axis.text.x = element_markdown(),
        panel.grid.major.x = element_blank(),
        legend.position = c(0.15, 0.85))

save_gg(file.path(outdir, "C1_devmap_coclustering_by_stage"), p3, 7, 5.3)

# --- BodyMap aggregated by tissue ------------------------------------------
bodymap_by_tissue <- bodymap_coclust %>%
  filter(tissue != "Constitutive") %>%
  group_by(tissue, proxiPhylogeny) %>%
  summarise(total_genes = sum(n_genes),
            total_partner_here = sum(n_partner_here), .groups = "drop") %>%
  mutate(pct = round(100 * total_partner_here / total_genes, 1))

tissue_sig <- build_aggregate_sig(bodymap_by_tissue, tissue)
bodymap_by_tissue <- bodymap_by_tissue %>%
  left_join(tissue_sig$sig_bars %>% select(tissue, proxiPhylogeny, sig),
            by = c("tissue", "proxiPhylogeny"))
tissue_axis_labels <- decorate_ratio_labels(
  as.character(levels(bodymap_by_tissue$tissue)),
  tissue_sig$sig_ratio %>%
    mutate(cluster = as.character(tissue)) %>%
    select(cluster, sig, enrichment))

p4 <- ggplot(bodymap_by_tissue, aes(x = tissue, y = pct, fill = proxiPhylogeny)) +
  geom_col(position = position_dodge(width = 0.7), width = 0.6) +
  geom_hline(data = tissue_sig$means,
             aes(yintercept = 100 * mean_rate, colour = proxiPhylogeny),
             linetype = "dashed", linewidth = 0.45, show.legend = FALSE) +
  geom_text(aes(label = sig, colour = proxiPhylogeny),
            position = position_dodge(width = 0.7),
            vjust = -1.3, size = 3.5, show.legend = FALSE) +
  geom_text(aes(label = paste0("n=", total_genes)),
            position = position_dodge(width = 0.7), vjust = -0.3, size = 2.5) +
  scale_fill_manual(values = redip_cols,
                    labels = c("AORe" = "Early", "LORe" = "Late"),
                    name = "Rediploidization") +
  scale_colour_manual(values = redip_cols, guide = "none") +
  scale_x_discrete(labels = setNames(tissue_axis_labels,
                                      levels(bodymap_by_tissue$tissue))) +
  labs(x = "Tissue", y = "Co-clustering rate (%)") +
  theme_bw(base_size = 11, base_family = font_family) +
  theme(axis.text.x = element_markdown(angle = 30, hjust = 1),
        panel.grid.major.x = element_blank(),
        legend.position = c(0.85, 0.85))

save_gg(file.path(outdir, "C1_bodymap_coclustering_by_tissue"), p4, 7, 5.3)

# =============================================================================
# Per-cluster gene composition (4-category stacked bars).
#
# Each SOM cluster's full Ssal gene roster is partitioned into:
#   Early      nSsal==2 & proxiPhylogeny==AORe   (red   #c0392b)
#   Late       nSsal==2 & proxiPhylogeny==LORe   (blue  #2980b9)
#   Singleton  nSsal==1                           (dark grey #7f8c8d)
#   Other      rest (nSsal>=3, cryptic, NA …)     (light grey #bdc3c7)
#
# Two panels per map: absolute counts and within-cluster proportion.
# Bottom-to-top stack order: Late, Early, Singleton, Other — keeps the two
# ohnolog categories adjacent and at the baseline for cross-cluster
# comparison.
#
# Cluster ID labels on the x-axis sit inside a coloured square using the
# SOM palette when the `ggtext` package is available; otherwise the script
# falls back to plain axis text (Diego can add the squares in Illustrator).
# =============================================================================
composition_cols <- c("Early"     = "#c0392b",
                      "Late"      = "#2980b9",
                      "Singleton" = "#7f8c8d",
                      "Other"     = "#bdc3c7")

# Stack order driven by data: biggest mean within-cluster proportion at the
# bottom, smallest at the top. Computed over non-constitutive clusters of
# BOTH maps so the category order is stable across DevMap and BodyMap
# panels (avoids confusing the reader with swapped stacks).
compute_composition_order <- function(composition_df, labels_df) {
  composition_df %>%
    left_join(labels_df, by = "cluster") %>%
    filter(label != "Constitutive") %>%
    group_by(category) %>% summarise(mean_pct = mean(pct), .groups = "drop") %>%
    arrange(desc(mean_pct)) %>% pull(category)
}
dev_order_src <- compute_composition_order(devmap_composition,  devmap_labels)
bm_order_src  <- compute_composition_order(bodymap_composition, bodymap_labels)

# Weighted merge: average of the two rankings so both maps stack identically.
# Factor level order: biggest-mean-pct first, smallest last. Combined with
# `position_stack(reverse = TRUE)` / `position_fill(reverse = TRUE)` in the
# plotting helpers, this places the biggest slice at the BOTTOM of the stack.
composition_levels <- names(sort(
  c(sapply(c("Early","Late","Singleton","Other"), function(cat) {
      (match(cat, dev_order_src) + match(cat, bm_order_src)) / 2
    })),
  decreasing = FALSE))   # ascending rank = biggest pct first
cat("Composition stack order (bottom→top):",
    paste(composition_levels, collapse = " → "), "\n")

# ggtext was made a hard dependency above (needed for bar-chart arrows);
# keep the fallback flag for future compatibility but it's now always TRUE.
use_ggtext <- TRUE

# Build "<span …>LABEL</span>" HTML that renders as a white-on-colour pill
# under ggtext::element_markdown(). palette_vec is named by the display label.
make_square_labels <- function(labels_in_order, palette_vec) {
  if (!use_ggtext) return(setNames(labels_in_order, labels_in_order))
  cols <- palette_vec[labels_in_order]
  # Pick black or white text depending on the palette colour brightness so
  # grey and yellow pills both read clearly.
  rgb_mat <- col2rgb(cols)
  lum     <- 0.299 * rgb_mat[1, ] + 0.587 * rgb_mat[2, ] + 0.114 * rgb_mat[3, ]
  fg      <- ifelse(lum > 150, "black", "white")
  html <- sprintf(
    "<span style='background-color:%s; color:%s; padding:1px 4px; border-radius:2px;'><b>%s</b></span>",
    cols, fg, labels_in_order)
  setNames(html, labels_in_order)
}

axis_x_theme <- if (use_ggtext) {
  theme(axis.text.x = element_markdown(angle = 45, hjust = 1))
} else {
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
}

# --- DevMap setup ----------------------------------------------------------
devmap_comp <- devmap_composition %>%
  filter(cluster != 9) %>%                                # drop P*
  mutate(
    cluster_label = devmap_label_map[as.character(cluster)],
    category      = factor(category, levels = composition_levels)
  ) %>%
  mutate(cluster_label = factor(
    cluster_label,
    levels = devmap_label_map[as.character(full_devmap_order)]))

devmap_label_html <- make_square_labels(
  labels_in_order = levels(devmap_comp$cluster_label),
  palette_vec     = devmap_cluster_cols)

devmap_comp_nc <- devmap_comp %>% filter(!cluster %in% devmap_constitutive)
devmap_nc_labels_html <- make_square_labels(
  labels_in_order = levels(droplevels(devmap_comp_nc$cluster_label)),
  palette_vec     = devmap_cluster_cols)

# --- BodyMap setup ---------------------------------------------------------
bodymap_comp <- bodymap_composition %>%
  mutate(category = factor(category, levels = composition_levels)) %>%
  left_join(bodymap_coclust %>% distinct(cluster, tissue) %>%
              mutate(cluster = as.integer(as.character(cluster))),
            by = "cluster") %>%
  mutate(tissue = factor(ifelse(is.na(tissue), "Constitutive",
                                 as.character(tissue)), levels = tissue_order),
         cluster = factor(cluster, levels = bodymap_cluster_order))

# For BodyMap, the x-axis is the raw cluster number inside its tissue facet;
# label pills use the tissue colour.
bm_cluster_to_tissue <- bodymap_comp %>% distinct(cluster, tissue) %>%
  mutate(tissue_col = tissue_cols[as.character(tissue)])
bodymap_label_html <- if (use_ggtext) {
  setNames(
    sprintf("<span style='background-color:%s; color:%s; padding:1px 3px; border-radius:2px;'><b>%s</b></span>",
            bm_cluster_to_tissue$tissue_col,
            ifelse(bm_cluster_to_tissue$tissue %in% c("Brain", "Constitutive"),
                   "black", "white"),
            as.character(bm_cluster_to_tissue$cluster)),
    as.character(bm_cluster_to_tissue$cluster))
} else {
  setNames(as.character(bm_cluster_to_tissue$cluster),
           as.character(bm_cluster_to_tissue$cluster))
}

bodymap_comp_nc <- bodymap_comp %>% filter(tissue != "Constitutive")

# --- plotting helpers ------------------------------------------------------
# One helper per map so we don't duplicate the position_fill / position_stack
# × faceting combinations four times.
# Per-cluster asterisk: one mark above each bar when ≥1 category cell
# deviates significantly from its genome-wide expectation. Colour = the
# category driving the deviation (biggest |log2(observed/expected)|
# among significant cells). Star count mirrors that driver's padj.
#
# We return one row per cluster with (x-axis value, colour driver,
# asterisk string). Empty for clusters with no significant deviation.
build_driver_marks <- function(sig_df, x_col) {
  sig_df %>%
    filter(sig != "") %>%
    mutate(abs_log2_fc = abs(log2(pmax(n, 0.5) / (total * p_cat)))) %>%
    group_by(cluster) %>%
    slice_max(abs_log2_fc, n = 1, with_ties = FALSE) %>%
    ungroup() %>%
    transmute(cluster, driver = as.character(category),
              sig, total) %>%
    # Return the user-supplied key (cluster_label or cluster) so the
    # caller can join by x-axis.
    rename(!!x_col := cluster)
}

# Build the per-cluster Early/Late composition bar panel for the DevMap map
# (`mode` = "prop" stacks to proportions; else raw counts) and save it via save_gg.
devmap_composition_plot <- function(df, mode, fname, labels_map, sig_df) {
  pos <- if (mode == "prop") position_fill(reverse = TRUE)
         else                 position_stack(reverse = TRUE)
  # Small expansion on top gives headroom for the asterisks.
  y_scale <- if (mode == "prop")
    scale_y_continuous(labels = scales::percent_format(accuracy = 1),
                       expand = expansion(mult = c(0, 0.08)))
  else
    scale_y_continuous(expand = expansion(mult = c(0, 0.08)))
  y_title <- if (mode == "prop") "Within-cluster gene composition"
             else "Gene count"

  # Per-cluster driver table joined on cluster → manuscript label via
  # devmap_label_map. Only clusters present in `df` are kept.
  cluster_to_label <- setNames(devmap_label_map,
                               names(devmap_label_map))
  marks <- sig_df %>%
    filter(sig != "", cluster %in% unique(df$cluster)) %>%
    mutate(abs_log2_fc = abs(log2(pmax(n, 0.5) / (total * p_cat)))) %>%
    group_by(cluster) %>%
    slice_max(abs_log2_fc, n = 1, with_ties = FALSE) %>%
    ungroup() %>%
    mutate(cluster_label = factor(
             cluster_to_label[as.character(cluster)],
             levels = levels(df$cluster_label)),
           driver = factor(as.character(category),
                           levels = c("Early","Late","Singleton","Other")),
           y_top  = if (mode == "prop") 1.0 else total)

  p <- ggplot(df, aes(x = cluster_label, y = n, fill = category)) +
    geom_col(position = pos, width = 0.7) +
    geom_text(data = marks,
              aes(x = cluster_label, y = y_top, label = sig, colour = driver),
              inherit.aes = FALSE, vjust = -0.3, size = 4.5,
              fontface = "bold", show.legend = FALSE) +
    scale_fill_manual(values = composition_cols, name = "Category",
                      breaks = c("Early", "Late", "Singleton", "Other")) +
    scale_colour_manual(values = composition_cols, guide = "none",
                        drop = FALSE) +
    scale_x_discrete(labels = labels_map) +
    y_scale +
    labs(x = "SOM cluster", y = y_title) +
    theme_bw(base_size = 11, base_family = font_family) +
    theme(axis.text.x = element_markdown(angle = 45, hjust = 1),
          panel.grid.major.x = element_blank(),
          legend.position    = "right")
  save_gg(fname, p, 10, 5)
}

# As devmap_composition_plot, but for the BodyMap map (tissue-grouped x axis).
bodymap_composition_plot <- function(df, mode, fname, labels_map, sig_df) {
  pos <- if (mode == "prop") position_fill(reverse = TRUE)
         else                 position_stack(reverse = TRUE)
  y_scale <- if (mode == "prop")
    scale_y_continuous(labels = scales::percent_format(accuracy = 1),
                       expand = expansion(mult = c(0, 0.08)))
  else
    scale_y_continuous(expand = expansion(mult = c(0, 0.08)))
  y_title <- if (mode == "prop") "Within-cluster gene composition"
             else "Gene count"

  # Match facet's (cluster, tissue) pair so the asterisk lands in the
  # correct tissue sub-panel — join on cluster then re-attach tissue.
  marks <- sig_df %>%
    mutate(cluster = as.character(cluster)) %>%
    filter(sig != "",
           cluster %in% as.character(unique(df$cluster))) %>%
    mutate(abs_log2_fc = abs(log2(pmax(n, 0.5) / (total * p_cat)))) %>%
    group_by(cluster) %>%
    slice_max(abs_log2_fc, n = 1, with_ties = FALSE) %>%
    ungroup() %>%
    left_join(df %>% distinct(cluster, tissue) %>%
                mutate(cluster = as.character(cluster)),
              by = "cluster") %>%
    mutate(cluster = factor(cluster, levels = levels(df$cluster)),
           driver  = factor(as.character(category),
                             levels = c("Early","Late","Singleton","Other")),
           y_top   = if (mode == "prop") 1.0 else total)

  p <- ggplot(df, aes(x = cluster, y = n, fill = category)) +
    geom_col(position = pos, width = 0.7) +
    geom_text(data = marks,
              aes(x = cluster, y = y_top, label = sig, colour = driver),
              inherit.aes = FALSE, vjust = -0.3, size = 3.2,
              fontface = "bold", show.legend = FALSE) +
    scale_fill_manual(values = composition_cols, name = "Category",
                      breaks = c("Early", "Late", "Singleton", "Other")) +
    scale_colour_manual(values = composition_cols, guide = "none",
                        drop = FALSE) +
    scale_x_discrete(labels = labels_map) +
    y_scale +
    facet_grid(~ tissue, scales = "free_x", space = "free_x") +
    labs(x = "SOM cluster", y = y_title) +
    theme_bw(base_size = 10, base_family = font_family) +
    theme(axis.text.x = element_markdown(angle = 45, hjust = 1, size = 7),
          strip.text = element_text(size = 7),
          panel.grid.major.x = element_blank(),
          legend.position    = "bottom")
  save_gg(fname, p, 14, 5)
}

dev_sig  <- devmap_composition_tests$tests %>%
  mutate(category = factor(category, levels = composition_levels))
bm_sig   <- bodymap_composition_tests$tests %>%
  mutate(category = factor(category, levels = composition_levels))

devmap_composition_plot(devmap_comp,    "count",
  file.path(outdir, "C1_devmap_composition_counts"),     devmap_label_html, dev_sig)
devmap_composition_plot(devmap_comp,    "prop",
  file.path(outdir, "C1_devmap_composition_proportion"), devmap_label_html, dev_sig)
devmap_composition_plot(devmap_comp_nc, "count",
  file.path(outdir, "C1_devmap_composition_counts_noconst"),     devmap_nc_labels_html, dev_sig)
devmap_composition_plot(devmap_comp_nc, "prop",
  file.path(outdir, "C1_devmap_composition_proportion_noconst"), devmap_nc_labels_html, dev_sig)

bodymap_composition_plot(bodymap_comp,    "count",
  file.path(outdir, "C1_bodymap_composition_counts"),     bodymap_label_html, bm_sig)
bodymap_composition_plot(bodymap_comp,    "prop",
  file.path(outdir, "C1_bodymap_composition_proportion"), bodymap_label_html, bm_sig)
bodymap_composition_plot(bodymap_comp_nc, "count",
  file.path(outdir, "C1_bodymap_composition_counts_noconst"),     bodymap_label_html, bm_sig)
bodymap_composition_plot(bodymap_comp_nc, "prop",
  file.path(outdir, "C1_bodymap_composition_proportion_noconst"), bodymap_label_html, bm_sig)

# =============================================================================
# NON-CONSTITUTIVE VERSIONS
# Same panels with C1-C4 / Constitutive dropped. These are the versions used
# in the main supplementary composite figures (Fig. SYY/SZZ Panel A),
# because constitutive clusters add noise to the stage/tissue-specific signal.
# =============================================================================

devmap_coclust_nc <- devmap_coclust_plot %>%
  filter(!cluster %in% devmap_constitutive)
nc_devmap_labels <- devmap_label_map[as.character(devmap_cluster_order_heatmap)]
nc_devmap_cluster_cols <- devmap_cluster_cols[nc_devmap_labels]

dev_nc_axis_labels <- decorate_ratio_labels(
  levels(droplevels(devmap_coclust_nc$cluster_label)), devmap_ratio,
  cluster_to_label_map = devmap_label_map)

p1_nc <- ggplot(devmap_coclust_nc, aes(x = cluster_label, y = pct_coclustered,
                                        fill = proxiPhylogeny)) +
  geom_col(position = position_dodge(width = 0.8), width = 0.7) +
  geom_hline(data = devmap_means,
             aes(yintercept = 100 * mean_rate, colour = proxiPhylogeny),
             linetype = "dashed", linewidth = 0.45, show.legend = FALSE) +
  geom_text(aes(label = sig, colour = proxiPhylogeny),
            position = position_dodge(width = 0.8),
            vjust = -1.2, size = 3.3, show.legend = FALSE) +
  geom_text(aes(label = n_genes),
            position = position_dodge(width = 0.8), vjust = -0.3, size = 2.2) +
  scale_fill_manual(values = redip_cols,
                    labels = c("AORe" = "Early", "LORe" = "Late"),
                    name = "Rediploidization") +
  scale_colour_manual(values = redip_cols, guide = "none") +
  scale_x_discrete(drop = TRUE,
                   labels = setNames(dev_nc_axis_labels,
                                      levels(droplevels(devmap_coclust_nc$cluster_label)))) +
  labs(x = "SOM cluster", y = "Co-clustering rate (%)") +
  theme_bw(base_size = 11, base_family = font_family) +
  theme(axis.text.x = element_markdown(angle = 45, hjust = 1),
        panel.grid.major.x = element_blank(),
        legend.position = c(0.85, 0.85))

save_gg(file.path(outdir, "C1_devmap_coclustering_per_cluster_noconst"), p1_nc, 10, 5.3)

bodymap_coclust_nc <- bodymap_coclust_plot %>% filter(tissue != "Constitutive")
bm_nc_cluster_order <- levels(droplevels(bodymap_coclust_nc$cluster))
bm_nc_axis_labels <- decorate_ratio_labels(
  bm_nc_cluster_order, bodymap_ratio,
  cluster_to_label_map = setNames(bm_nc_cluster_order, bm_nc_cluster_order))

p2_nc <- ggplot(bodymap_coclust_nc, aes(x = cluster, y = pct_coclustered,
                                         fill = proxiPhylogeny)) +
  geom_col(position = position_dodge(width = 0.8), width = 0.7) +
  geom_hline(data = bodymap_means,
             aes(yintercept = 100 * mean_rate, colour = proxiPhylogeny),
             linetype = "dashed", linewidth = 0.4, show.legend = FALSE) +
  geom_text(aes(label = sig, colour = proxiPhylogeny),
            position = position_dodge(width = 0.8),
            vjust = -0.8, size = 2.6, show.legend = FALSE) +
  scale_fill_manual(values = redip_cols,
                    labels = c("AORe" = "Early", "LORe" = "Late"),
                    name = "Rediploidization") +
  facet_grid(~ tissue, scales = "free_x", space = "free_x") +
  scale_colour_manual(values = redip_cols, guide = "none") +
  scale_x_discrete(labels = setNames(bm_nc_axis_labels, bm_nc_cluster_order)) +
  facet_grid(~ tissue, scales = "free_x", space = "free_x") +
  labs(x = "SOM cluster", y = "Co-clustering rate (%)") +
  theme_bw(base_size = 10, base_family = font_family) +
  theme(axis.text.x = element_markdown(angle = 45, hjust = 1, size = 7),
        strip.text = element_text(size = 7),
        panel.grid.major.x = element_blank(),
        legend.position = "bottom")

save_gg(file.path(outdir, "C1_bodymap_coclustering_per_cluster_noconst"), p2_nc, 14, 5)

cat("All figures saved.\n")
