#!/usr/bin/env Rscript
# =============================================================================
# 03d_ohnolog_sankey.R
# -----------------------------------------------------------------------------
# Purpose
#   Alluvial (Sankey) diagrams of ohnolog pair SOM cluster assignments, one per
#   (map × rediploidization class × constitutive filter) combination. Ribbon
#   width = number of pairs connecting two clusters; ribbon colour = log2
#   observed/expected under random pairing (skyblue = depleted, seashell =
#   expected, lightcoral = enriched).
#
# Inputs
#   <data_path>/c1_coclustering_results.RData   (generated by 03)
#     Provides `devmap_result`, `bodymap_result` — each a list with a `$detail`
#     data frame containing one row per ohnolog pair with columns
#     `cluster1`, `cluster2` (raw SOM unit IDs) and `proxiPhylogeny` ∈
#     {AORe, LORe}.
#   <data_path>/c1_extended_results.RData        (generated by 03b, for completeness)
#   data/ohnolog/som_info.RData                     (for `sb_som_info`, which
#     carries `class_max` and `constitutive_class` per BodyMap cluster).
#
# Outputs → <outdir>/panels/
#   C1_{devmap,bodymap}_sankey_{early,late}[.noconst].{pdf,png}
#
# Key choices
#   * Expected ribbon size under the null of random pairing is derived from
#     gene marginals: for each gene copy, P(in cluster k) = n_k / N_genes.
#     Given `n_pairs` total pairs and classical 2-gene-per-pair counting:
#       E(A,B) = n_pairs * 2 * p_A * p_B   for A ≠ B
#       E(A,A) = n_pairs *     p_A * p_B   for A = B   (no factor-of-2)
#     `pmax(expected, 0.5)` floor avoids divide-by-zero / -Inf when a cluster
#     pair never co-occurs in the observed data.
#   * Colour legend uses a phantom zero-size point (geom_point) so ggplot
#     generates a continuous colourbar for the manually-coloured ribbons.
#   * P* (unit 9) excluded from DevMap throughout.
# =============================================================================

suppressPackageStartupMessages({
  library(tidyverse)
  library(ggalluvial)
  library(viridisLite)
  library(scales)
})

# --- Global font (Helvetica) ------------------------------------------------
font_family <- "Helvetica"
theme_set(theme_bw(base_size = 11, base_family = font_family))
update_geom_defaults("text",  list(family = font_family))
update_geom_defaults("label", list(family = font_family))

outdir    <- "results/ohnolog/panels"
data_path <- "results/ohnolog/data"

# --- Load data ---
load(file.path(data_path, "c1_coclustering_results.RData"))
load(file.path(data_path, "c1_extended_results.RData"))

load("data/ohnolog/som_info.RData")

# =================================================================
# SHARED PALETTE (identical logic across 03c / 03d / 03e)
# =================================================================
inferno_cols <- rev(inferno(12, begin = 0.15, end = 0.9))
desired_order <- c(13, 10, 15, 14, 16, 12, 4, 2, 1, 6, 9, 5, 3, 8, 11, 7)
palette_idx   <- match(1:16, desired_order)
full_pal_16   <- c(inferno_cols, rep("#becacaff", 4))[palette_idx]
names(full_pal_16) <- as.character(1:16)

devmap_label_map <- c(
  "13"="M1","10"="M2","15"="M3","14"="M4",
  "16"="B1","12"="B2","4"="G1","2"="S1","1"="S2",
  "6"="P1","5"="P2",
  "7"="C1","11"="C2","8"="C3","3"="C4"
)
devmap_cluster_order <- c(13,10,15,14,16,12,4,2,1,6,5,7,11,8,3)
devmap_label_order   <- unname(devmap_label_map[as.character(devmap_cluster_order)])
devmap_constitutive  <- c(7, 11, 8, 3)

# Named palette keyed by LABEL
devmap_palette <- setNames(
  full_pal_16[as.character(devmap_cluster_order)],
  devmap_label_order
)

# --- BodyMap tissue setup ---
# Collapse a BodyMap cluster's `class_max` into an abbreviated tissue label.
# Abbreviations are used here (HK, Int., Const.) rather than full names so
# the stratum labels fit inside the Sankey bars.
# Args:  cluster_num — integer BodyMap SOM unit index (1..36).
# Returns: character tissue tag in `tissue_order`.
bodymap_tissue_for_cluster <- function(cluster_num) {
  info <- sb_som_info[cluster_num, ]
  if (!is.null(info$constitutive_class) && info$constitutive_class == "TRUE") return("Const.")
  cm <- info$class_max
  case_when(
    grepl("Brain", cm) ~ "Brain", grepl("Muscle", cm) ~ "Muscle",
    grepl("Liver", cm) ~ "Liver", grepl("Testes", cm) ~ "Testes",
    grepl("Ova", cm) ~ "Ovary", grepl("Gill", cm) ~ "Gill",
    grepl("HeadKidney", cm) ~ "HK", grepl("Intestine", cm) ~ "Int.",
    TRUE ~ "Multi"
  )
}

bm_labels <- sapply(1:36, function(i) paste0(bodymap_tissue_for_cluster(i), i))
names(bm_labels) <- as.character(1:36)

tissue_cols <- c("Brain"="#dce648ff","Muscle"="salmon","Liver"="#8a0000ff",
  "Testes"="forestgreen","Ovary"="#ffa300ff","Gill"="red2",
  "HK"="black","Int."="hotpink","Multi"="skyblue","Const."="#becacaff")

bm_palette <- sapply(1:36, function(i) tissue_cols[bodymap_tissue_for_cluster(i)])
names(bm_palette) <- bm_labels

bm_tissue_type <- sapply(1:36, bodymap_tissue_for_cluster)
tissue_order   <- c("Brain","Muscle","Gill","HK","Int.","Liver","Testes","Ovary","Multi","Const.")
bm_order_idx   <- order(match(bm_tissue_type, tissue_order), 1:36)
bm_label_order <- bm_labels[bm_order_idx]

bm_constitutive <- which(sapply(1:36, function(i)
  !is.null(sb_som_info[i,]$constitutive_class) && sb_som_info[i,]$constitutive_class == "TRUE"))

# -----------------------------------------------------------------------------
# BodyMap Sankey is drawn at DOMINANT-TISSUE resolution: 36 SOM clusters is
# unreadable as an alluvial diagram. Each raw SOM unit id is collapsed to its
# tissue tag; multi-tissue clusters fold into their peak-expression tissue
# (bodymap_tissue_for_cluster already returns that), so no ohnolog pairs are
# dropped. compute_flows() then aggregates pairs — and the O/E null — at the
# tissue level. DevMap stays at cluster resolution (15 strata is legible).
# -----------------------------------------------------------------------------
bm_cluster_to_tissue <- setNames(bm_tissue_type, as.character(1:36))
collapse_bodymap_detail <- function(detail_df) {
  detail_df %>%
    mutate(cluster1 = unname(bm_cluster_to_tissue[as.character(cluster1)]),
           cluster2 = unname(bm_cluster_to_tissue[as.character(cluster2)]))
}
# No cluster collapses to "Multi" (every class_max carries a tissue token), so
# the Sankey strata are the eight tissues + Const. label_map is the identity.
bm_tissue_order  <- setdiff(tissue_order, "Multi")
bm_tissue_lblmap <- setNames(bm_tissue_order, bm_tissue_order)

# O/E colour scale (skyblue → seashell → lightcoral)
oe_palette <- colorRampPalette(c("skyblue", "seashell", "lightcoral"))

# Save a ggplot to paired PDF + PNG outputs, routed into
# panels/{pdf|png}/{devmap|bodymap}/{const|noconst}/ by filename pattern
# (see 03c for full docstring).
# Manuscript-pack mirror: for the `const` Sankey panels that are spliced into
# the R1 revision figure pack, write a second copy under manuscript_R1_panels/
# with the canonical Fig_S{YY,ZZ}_* filename. Keep in sync with the README in
# manuscript_R1_panels/. `noconst` variants are not mirrored.
manuscript_pack_dir <- "results/ohnolog/panels"
manuscript_pack_map <- c(
  C1_devmap_sankey_early   = "Fig_SYY_B_DevMap_sankey_Early",
  C1_devmap_sankey_late    = "Fig_SYY_B_DevMap_sankey_Late",
  C1_bodymap_sankey_early  = "Fig_SZZ_B_BodyMap_sankey_Early",
  C1_bodymap_sankey_late   = "Fig_SZZ_B_BodyMap_sankey_Late"
)

save_gg <- function(fname_base, p, w, h, dpi = 300) {
  name    <- basename(fname_base)
  map     <- if (grepl("_bodymap_", name)) "bodymap" else "devmap"
  variant <- if (grepl("_noconst$", name)) "noconst" else "const"
  pdf_dir <- file.path(outdir, "pdf", map, variant)
  png_dir <- file.path(outdir, "png", map, variant)
  dir.create(pdf_dir, showWarnings = FALSE, recursive = TRUE)
  dir.create(png_dir, showWarnings = FALSE, recursive = TRUE)
  ggsave(file.path(pdf_dir, paste0(name, ".pdf")), p, width = w, height = h)
  ggsave(file.path(png_dir, paste0(name, ".png")), p, width = w, height = h, dpi = dpi)
  cat("  Saved", name, "→", map, "/", variant, "\n")
  if (name %in% names(manuscript_pack_map)) {
    pack_name <- manuscript_pack_map[[name]]
    ggsave(file.path(manuscript_pack_dir, paste0(pack_name, ".pdf")),
           p, width = w, height = h)
    ggsave(file.path(manuscript_pack_dir, paste0(pack_name, ".png")),
           p, width = w, height = h, dpi = dpi)
    cat("  Mirrored → manuscript_R1_panels/", pack_name, "\n", sep = "")
  }
}

# -----------------------------------------------------------------------------
# make_sankey — render a two-stratum alluvial diagram of ohnolog pair flows
# between SOM clusters, coloured by log2 observed/expected.
#
# Args:
#   detail_df     — data frame of pairs with `cluster1`, `cluster2` (raw IDs).
#   label_map     — named char vector mapping raw ID (as string) → display label.
#   label_order   — display labels in the desired left-to-right stratum order.
#   strat_palette — named char vector: display label → fill colour.
#   title_text    — (currently unused; kept for future annotation).
#   fname_base    — output path without extension.
#   fig_w, fig_h  — canvas size in inches.
#   text_size     — stratum label point size (shrink for BodyMap's 36 strata).
# Returns: invisible NULL (saves files as side effect).
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# compute_flows — purely computational: take a detail frame and return the
# (clust_a, clust_b, observed, expected, log2_oe) tibble. Shared between
# the global-range pre-pass (so all Sankeys use the same colour scale) and
# the make_sankey plotting step.
# -----------------------------------------------------------------------------
compute_flows <- function(detail_df) {
  all_genes   <- c(detail_df$cluster1, detail_df$cluster2)
  gene_counts <- table(all_genes)
  total_genes <- length(all_genes)
  n_pairs     <- nrow(detail_df)

  detail_df %>%
    mutate(clust_a = pmin(cluster1, cluster2),
           clust_b = pmax(cluster1, cluster2)) %>%
    count(clust_a, clust_b, name = "observed") %>%
    mutate(
      p_a = as.numeric(gene_counts[as.character(clust_a)]) / total_genes,
      p_b = as.numeric(gene_counts[as.character(clust_b)]) / total_genes,
      expected = ifelse(clust_a == clust_b,
                        n_pairs * p_a * p_b,
                        n_pairs * 2 * p_a * p_b),
      oe_ratio = observed / pmax(expected, 0.5),
      log2_oe  = log2(oe_ratio)
    )
}

# -----------------------------------------------------------------------------
# make_sankey — render a two-stratum alluvial diagram. `oe_limits` MUST be
# provided and is shared across ALL Sankeys in this script so the colour
# encoding is directly comparable between panels and maps (a ribbon at
# log2(O/E) = 1 looks the same everywhere).
# -----------------------------------------------------------------------------
make_sankey <- function(detail_df, label_map, label_order, strat_palette,
                        title_text, fname_base, oe_limits,
                        fig_w = 8, fig_h = 10, text_size = 2.3,
                        x_unit = "SOM cluster") {

  flows <- compute_flows(detail_df)

  # Ribbon colour: map clamped log2(O/E) onto [skyblue, seashell, lightcoral]
  # using the GLOBAL limits so all Sankeys are directly comparable.
  n_col    <- 256
  clamped  <- pmin(pmax(flows$log2_oe, oe_limits[1]), oe_limits[2])
  rescaled <- (clamped - oe_limits[1]) / diff(oe_limits)
  flows$ribbon_col <- oe_palette(n_col)[1 + round(rescaled * (n_col - 1))]

  flows <- flows %>%
    mutate(
      label_a = label_map[as.character(clust_a)],
      label_b = label_map[as.character(clust_b)],
      source  = paste0(label_a, " "),
      target  = paste0(" ", label_b)
    )
  source_levels <- paste0(label_order, " ")
  target_levels <- paste0(" ", label_order)
  flows$source <- factor(flows$source, levels = source_levels)
  flows$target <- factor(flows$target, levels = target_levels)

  left_cols  <- setNames(strat_palette[label_order], source_levels)
  right_cols <- setNames(strat_palette[label_order], target_levels)

  # Ribbons get colour via I(ribbon_col) (bypasses ggplot scale machinery).
  # Phantom point below drives the shared colour-bar legend — its log2_oe
  # endpoints are set to the global range so the legend is identical in
  # every Sankey panel.
  phantom <- data.frame(x = c(1, 1), y = c(0, 0), log2_oe = oe_limits)

  p <- ggplot(flows, aes(axis1 = source, axis2 = target, y = observed)) +
    geom_alluvium(aes(fill = I(ribbon_col)), alpha = 0.7, width = 1/5) +
    geom_stratum(aes(fill = after_stat(stratum)), width = 1/5,
                 colour = "grey30", linewidth = 0.3) +
    geom_text(stat = "stratum", aes(label = after_stat(stratum)),
              size = text_size, fontface = "bold") +
    geom_point(data = phantom, aes(x = x, y = y, colour = log2_oe),
               size = 0, inherit.aes = FALSE, show.legend = TRUE) +
    scale_fill_manual(values = c(left_cols, right_cols), guide = "none") +
    scale_colour_gradientn(
      colours = c("skyblue", "seashell", "lightcoral"),
      name    = expression(log[2](O/E)),
      limits  = oe_limits,
      guide   = guide_colorbar(barwidth = 0.8, barheight = 5)
    ) +
    scale_x_discrete(limits = c(paste0("Copy 1\n", x_unit),
                                paste0("Copy 2\n", x_unit)),
                     expand = c(0.15, 0.05)) +
    labs(y = "Number of ohnolog pairs") +
    theme_minimal(base_size = 11, base_family = font_family) +
    theme(panel.grid = element_blank(),
          axis.text.y = element_blank(),
          axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          legend.position = "right")

  save_gg(fname_base, p, fig_w, fig_h)
}

# =================================================================
# Global O/E range across every Sankey we are about to draw
# -----------------------------------------------------------------
# Collect all flows from all 8 Sankeys (2 maps × 2 classes × 2 const
# variants). Take the union's range and make it symmetric about zero
# so the diverging palette stays centred on log2(O/E) = 0 (no
# observed-expected deviation) — lightcoral above, skyblue below.
# =================================================================
collect_all_flows <- function() {
  combos <- list(
    list(det = devmap_result$detail %>% filter(proxiPhylogeny == "AORe", cluster1 != 9, cluster2 != 9)),
    list(det = devmap_result$detail %>% filter(proxiPhylogeny == "LORe", cluster1 != 9, cluster2 != 9)),
    # BodyMap flows collapsed to tissue level (matches how the Sankeys are drawn)
    list(det = collapse_bodymap_detail(bodymap_result$detail %>% filter(proxiPhylogeny == "AORe"))),
    list(det = collapse_bodymap_detail(bodymap_result$detail %>% filter(proxiPhylogeny == "LORe"))),
    # noconst variants
    list(det = devmap_result$detail %>%
           filter(proxiPhylogeny == "AORe", cluster1 != 9, cluster2 != 9,
                  !cluster1 %in% devmap_constitutive, !cluster2 %in% devmap_constitutive)),
    list(det = devmap_result$detail %>%
           filter(proxiPhylogeny == "LORe", cluster1 != 9, cluster2 != 9,
                  !cluster1 %in% devmap_constitutive, !cluster2 %in% devmap_constitutive)),
    list(det = collapse_bodymap_detail(bodymap_result$detail %>%
           filter(proxiPhylogeny == "AORe",
                  !cluster1 %in% bm_constitutive, !cluster2 %in% bm_constitutive))),
    list(det = collapse_bodymap_detail(bodymap_result$detail %>%
           filter(proxiPhylogeny == "LORe",
                  !cluster1 %in% bm_constitutive, !cluster2 %in% bm_constitutive)))
  )
  unlist(lapply(combos, function(x) compute_flows(x$det)$log2_oe))
}
.all_log2_oe <- collect_all_flows()
# Trim extreme outliers (top / bottom 1% quantiles) so a single rare flow
# doesn't expand the scale and squash the rest of the signal.
.oe_q        <- quantile(.all_log2_oe,
                          probs = c(0.01, 0.99),
                          na.rm = TRUE)
global_oe_limits <- c(-1, 1) * max(abs(.oe_q))
cat(sprintf("Global log2(O/E) range across all Sankeys: [%.2f, %.2f]\n",
            global_oe_limits[1], global_oe_limits[2]))

# =================================================================
# DevMap Sankeys
# =================================================================
cat("=== DevMap Sankeys ===\n")

for (redip in c("AORe", "LORe")) {
  detail_sub <- devmap_result$detail %>%
    filter(proxiPhylogeny == redip, cluster1 != 9, cluster2 != 9)
  lbl <- ifelse(redip == "AORe", "Early", "Late")

  make_sankey(detail_sub, devmap_label_map, devmap_label_order, devmap_palette,
    paste0("DevMap ", lbl, " rediploidization"),
    file.path(outdir, paste0("C1_devmap_sankey_", tolower(lbl))),
    oe_limits = global_oe_limits)

  # Non-constitutive
  nc_detail <- detail_sub %>%
    filter(!cluster1 %in% devmap_constitutive, !cluster2 %in% devmap_constitutive)
  nc_labels  <- devmap_label_order[!devmap_label_order %in% c("C1","C2","C3","C4")]
  nc_palette <- devmap_palette[nc_labels]

  make_sankey(nc_detail, devmap_label_map, nc_labels, nc_palette,
    paste0("DevMap ", lbl, " (stage-specific only)"),
    file.path(outdir, paste0("C1_devmap_sankey_", tolower(lbl), "_noconst")),
    oe_limits = global_oe_limits)
}

# =================================================================
# BodyMap Sankeys
# =================================================================
cat("\n=== BodyMap Sankeys ===\n")

for (redip in c("AORe", "LORe")) {
  detail_sub <- bodymap_result$detail %>% filter(proxiPhylogeny == redip)
  lbl <- ifelse(redip == "AORe", "Early", "Late")

  # Collapse to tissue level (multi clusters → peak tissue) before drawing.
  make_sankey(collapse_bodymap_detail(detail_sub),
    bm_tissue_lblmap, bm_tissue_order, tissue_cols,
    paste0("BodyMap ", lbl, " rediploidization"),
    file.path(outdir, paste0("C1_bodymap_sankey_", tolower(lbl))),
    oe_limits = global_oe_limits,
    fig_w = 7, fig_h = 8, text_size = 3, x_unit = "tissue")

  # Non-constitutive: drop constitutive clusters on raw ids, then collapse.
  nc_detail <- detail_sub %>%
    filter(!cluster1 %in% bm_constitutive, !cluster2 %in% bm_constitutive)
  nc_tissue_order <- setdiff(bm_tissue_order, "Const.")

  make_sankey(collapse_bodymap_detail(nc_detail),
    bm_tissue_lblmap, nc_tissue_order, tissue_cols,
    paste0("BodyMap ", lbl, " (tissue-specific only)"),
    file.path(outdir, paste0("C1_bodymap_sankey_", tolower(lbl), "_noconst")),
    oe_limits = global_oe_limits,
    fig_w = 7, fig_h = 7, text_size = 3, x_unit = "tissue")
}

cat("\nDone.\n")
