#!/usr/bin/env Rscript
# =============================================================================
# 03e_ohnolog_upset.R
# -----------------------------------------------------------------------------
# Purpose
#   UpSet plots of ohnolog pair SOM sharing. Each ohnolog pair → one row in a
#   binary set-membership matrix:
#     * Co-clustered pair  (both copies in cluster X) → single-dot column at X.
#     * Cross-cluster pair (copies in X and Y)        → two-dot column at X,Y.
#   Top bars count pairs per intersection; left bars count gene copies per set.
#
# Inputs
#   <data_path>/c1_coclustering_results.RData  (generated by 03 — devmap_result, bodymap_result)
#   data/ohnolog/som_info.RData                (sb_som_info for tissue mapping)
#
# Outputs → <outdir>/panels/
#   C1_{devmap,bodymap}_upset_{early,late}[.noconst].{pdf,png}
#
# UpSetR gotcha (why this script looks the way it does)
#   UpSetR's `upset()` has two code paths:
#     (a) Counter path      — invoked when `intersections` is NOT passed.
#                              Respects `sets + keep.order` for the left axis.
#     (b) specific path     — invoked when `intersections` IS passed. It
#                              internally calls `unique(unlist(intersections))`
#                              and DISCARDS the `sets` argument, so the left-
#                              axis order (and colour mapping) is determined
#                              by the intersection list, not by `sets`.
#   We want dev-stage / tissue order on the left axis, so we deliberately
#   take path (a) and let `order.by = "freq"` handle the top-bar sort.
#   (Also recorded in ~/.claude memory: `feedback_upsetr_colors.md`.)
#
# Key choices
#   * All bars black; no grey/black split, no query overlays. The prior
#     "same vs other cluster" colour split was rolled back for simplicity.
#   * Sets ordered bottom→top on the left axis because UpSetR draws sets
#     from the bottom; we `rev()` the label order before passing to `sets`.
#   * P* (unit 9) excluded from DevMap.
# =============================================================================

suppressPackageStartupMessages({
  library(tidyverse)
  library(UpSetR)
  library(viridisLite)
})

# --- Global font (Helvetica) ------------------------------------------------
# UpSetR draws via base graphics; set par(family=...) before each device so
# axis and bar labels render in Helvetica. ggplot components inherit from
# theme_set.
font_family <- "Helvetica"
theme_set(theme_bw(base_size = 11, base_family = font_family))

outdir    <- "results/ohnolog/panels"
data_path <- "results/ohnolog/data"

# --- Load data ---
load(file.path(data_path, "c1_coclustering_results.RData"))

# =================================================================
# SHARED PALETTE: DevMap inferno (rev'd: M1=yellow, P2=dark)
# Identical to 03c and 03d.
# =================================================================
inferno_cols <- rev(inferno(12, begin = 0.15, end = 0.9))
constitutive_col <- "#becacaff"
desired_order <- c(13, 10, 15, 14, 16, 12, 4, 2, 1, 6, 9, 5, 3, 8, 11, 7)
palette_idx  <- match(1:16, desired_order)
full_pal_16  <- c(inferno_cols, rep(constitutive_col, 4))[palette_idx]
names(full_pal_16) <- as.character(1:16)

devmap_label_map <- c(
  "13"="M1","10"="M2","15"="M3","14"="M4",
  "16"="B1","12"="B2","4"="G1","2"="S1","1"="S2",
  "6"="P1","5"="P2",
  "7"="C1","11"="C2","8"="C3","3"="C4"
)
devmap_cluster_order <- c(13,10,15,14,16,12,4,2,1,6,5,7,11,8,3)
devmap_label_order   <- unname(devmap_label_map[as.character(devmap_cluster_order)])
devmap_constitutive  <- c(7, 11, 8, 3)

devmap_palette <- setNames(
  full_pal_16[as.character(devmap_cluster_order)],
  devmap_label_order
)

# Save a base-graphics plot (UpSetR uses grid/base) to paired PDF + PNG. We
# can't use ggsave here because UpSetR returns a grid object plotted via
# print(), not a ggplot.
# Args:
#   fname_base — output path without extension.
#   plot_fn    — zero-argument function that draws the plot to the active device.
#   w, h       — dimensions in inches.
#   png_dpi    — raster resolution for PNG.
save_pdf_png <- function(fname_base, plot_fn, w, h, png_dpi = 300) {
  # Route into panels/{pdf|png}/{devmap|bodymap}/{const|noconst}/ — see 03c.
  name    <- basename(fname_base)
  map     <- if (grepl("_bodymap_", name)) "bodymap" else "devmap"
  variant <- if (grepl("_noconst$", name)) "noconst" else "const"
  pdf_dir <- file.path(outdir, "pdf", map, variant)
  png_dir <- file.path(outdir, "png", map, variant)
  dir.create(pdf_dir, showWarnings = FALSE, recursive = TRUE)
  dir.create(png_dir, showWarnings = FALSE, recursive = TRUE)
  pdf_path <- file.path(pdf_dir, paste0(name, ".pdf"))
  png_path <- file.path(png_dir, paste0(name, ".png"))
  # Set graphics family to Helvetica before each device so UpSetR's base
  # graphics call honours it; restore on device close.
  cairo_pdf(pdf_path, width = w, height = h, family = font_family)
  plot_fn(); dev.off()
  # UpSetR's print() calls grid.newpage() internally, leaving a blank first
  # page in the PDF. Strip it post-hoc so Illustrator opens to the plot.
  if (requireNamespace("qpdf", quietly = TRUE)) {
    n <- qpdf::pdf_length(pdf_path)
    if (n > 1) {
      tmp <- sub("\\.pdf$", "_FIXED.pdf", pdf_path)
      qpdf::pdf_subset(pdf_path, pages = 2:n, output = tmp)
      file.rename(tmp, pdf_path)
    }
  }
  png(png_path, width = w, height = h, units = "in", res = png_dpi,
      family = font_family)
  plot_fn(); dev.off()
  cat("  Saved", name, "→", map, "/", variant, "\n")
}

# -----------------------------------------------------------------------------
# make_upset_plot — cluster-level UpSet for DevMap ohnolog pairs.
#
# Each pair contributes one row to a 0/1 membership matrix over `label_order`.
# For a co-clustered pair both `lab1` and `lab2` resolve to the same column,
# so the `mat[i, lab1] <- 1; mat[i, lab2] <- 1` sequence produces a single-dot
# intersection (the second write is a no-op). Cross-cluster pairs produce a
# two-dot intersection.
#
# Args:
#   detail_df     — pairs data frame with `cluster1`, `cluster2`.
#   label_map     — raw SOM ID (string) → manuscript label.
#   label_order   — manuscript labels in desired left-axis order (top→bottom).
#   strat_palette — named char: label → bar colour (for left set-bars only).
#   fname_base    — output path without extension.
#   fig_w, fig_h  — size in inches.
# -----------------------------------------------------------------------------
make_upset_plot <- function(detail_df, label_map, label_order, strat_palette,
                            fname_base, fig_w = 14, fig_h = 8) {

  # Map cluster numbers to manuscript labels
  df <- detail_df %>%
    mutate(lab1 = label_map[as.character(cluster1)],
           lab2 = label_map[as.character(cluster2)]) %>%
    filter(lab1 %in% label_order, lab2 %in% label_order)

  # Binary membership matrix: one row per ohnolog pair
  # Co-clustered pair → one column set; cross-cluster → two columns set
  mat <- matrix(0L, nrow = nrow(df), ncol = length(label_order),
                dimnames = list(NULL, label_order))
  for (i in seq_len(nrow(df))) {
    mat[i, df$lab1[i]] <- 1L
    mat[i, df$lab2[i]] <- 1L  # same column if co-clustered → no-op
  }

  active_sets <- label_order[colSums(mat) > 0]
  mat <- mat[, active_sets, drop = FALSE]
  upset_df <- as.data.frame(mat, check.names = FALSE)

  # UpSetR: Counter() path (no intersections param) → sets + keep.order works
  # rev() because UpSetR plots bottom-to-top
  # UpSetR draws sets bottom→top on the left axis, so reverse the display
  # order before passing to `sets`.
  set_order <- rev(active_sets)

  plot_args <- list(
    data = upset_df,
    sets = set_order,          # path (a): Counter path; respects keep.order
    keep.order = TRUE,
    nsets = length(set_order),
    nintersects = 40,          # top-40 intersections shown (was 30)
    mb.ratio = c(0.55, 0.45),
    main.bar.color = "black",
    matrix.color = "black",
    sets.bar.color = unname(strat_palette[set_order]),
    mainbar.y.label = "Ohnolog pairs",
    sets.x.label = "Genes in set",
    # text.scale slots: c(intersection-size axis title, intersection-size
    # tick labels, set-size axis title, set-size tick labels, set-name
    # labels, intersection-count labels on top of bars). Bumped throughout;
    # last slot (intersection-count labels) bumped hardest per Diego.
    text.scale = c(1.5, 1.3, 1.2, 1.1, 1.3, 1.1),
    set_size.show = TRUE,
    set_size.numbers_size = 6,
    show.numbers = "yes",
    number.angles = 25,
    order.by = "freq"
  )

  cat("  Set order (bottom→top):", paste(set_order, collapse = ", "), "\n")
  cat("  Total pairs:", nrow(df), " | Co-clustered:",
      sum(df$lab1 == df$lab2), " | Cross-cluster:",
      sum(df$lab1 != df$lab2), "\n")

  plot_fn <- function() do.call(print, list(do.call(upset, plot_args)))
  save_pdf_png(fname_base, plot_fn, fig_w, fig_h)
}

# =================================================================
# BodyMap UpSet: tissue-level aggregation
# =================================================================
# -----------------------------------------------------------------------------
# make_tissue_upset — BodyMap tissue-level UpSet.
#
# Identical structure to make_upset_plot but aggregates the 36 BodyMap SOM
# clusters into ~10 tissue categories first (via `tissue_map`), so sets are
# tissues rather than individual clusters. "Within-tissue" pairs land in
# single-dot columns; "cross-tissue" in two-dot columns.
# -----------------------------------------------------------------------------
make_tissue_upset <- function(detail_df, tissue_map, tissue_order, tissue_palette,
                              fname_base, fig_w = 14, fig_h = 8) {

  df <- detail_df %>%
    mutate(t1 = tissue_map[as.character(cluster1)],
           t2 = tissue_map[as.character(cluster2)]) %>%
    filter(t1 %in% tissue_order, t2 %in% tissue_order)

  mat <- matrix(0L, nrow = nrow(df), ncol = length(tissue_order),
                dimnames = list(NULL, tissue_order))
  for (i in seq_len(nrow(df))) {
    mat[i, df$t1[i]] <- 1L
    mat[i, df$t2[i]] <- 1L
  }

  active_tissues <- tissue_order[colSums(mat) > 0]
  mat <- mat[, active_tissues, drop = FALSE]
  upset_df <- as.data.frame(mat, check.names = FALSE)

  set_order <- rev(active_tissues)

  plot_args <- list(
    data = upset_df,
    sets = set_order,
    keep.order = TRUE,
    nsets = length(set_order),
    nintersects = 30,
    mb.ratio = c(0.55, 0.45),
    main.bar.color = "black",
    matrix.color = "black",
    sets.bar.color = unname(tissue_palette[set_order]),
    mainbar.y.label = "Ohnolog pairs",
    sets.x.label = "Genes in set",
    text.scale = c(1.3, 1, 1, 0.9, 1.1, 0.65),
    set_size.show = TRUE,
    set_size.numbers_size = 6,
    show.numbers = "yes",
    number.angles = 25,
    order.by = "freq"
  )

  cat("  Set order (bottom→top):", paste(set_order, collapse = ", "), "\n")
  cat("  Total pairs:", nrow(df), " | Within-tissue:",
      sum(df$t1 == df$t2), " | Cross-tissue:",
      sum(df$t1 != df$t2), "\n")

  plot_fn <- function() do.call(print, list(do.call(upset, plot_args)))
  save_pdf_png(fname_base, plot_fn, fig_w, fig_h)
}

# =================================================================
# Generate DevMap UpSet plots
# =================================================================
cat("=== DevMap UpSet ===\n")

for (redip in c("AORe", "LORe")) {
  detail_sub <- devmap_result$detail %>%
    filter(proxiPhylogeny == redip, cluster1 != 9, cluster2 != 9)
  lbl <- ifelse(redip == "AORe", "Early", "Late")

  make_upset_plot(detail_sub, devmap_label_map, devmap_label_order, devmap_palette,
    file.path(outdir, paste0("C1_devmap_upset_", tolower(lbl))))

  nc_detail <- detail_sub %>%
    filter(!cluster1 %in% devmap_constitutive, !cluster2 %in% devmap_constitutive)
  nc_labels <- devmap_label_order[!devmap_label_order %in% c("C1","C2","C3","C4")]
  nc_palette <- devmap_palette[nc_labels]

  make_upset_plot(nc_detail, devmap_label_map, nc_labels, nc_palette,
    file.path(outdir, paste0("C1_devmap_upset_", tolower(lbl), "_noconst")))
}

# =================================================================
# Generate BodyMap UpSet plots
# =================================================================
cat("\n=== BodyMap UpSet ===\n")

load("data/ohnolog/som_info.RData")

# Collapse BodyMap cluster → dominant tissue (full names used here, unlike
# the abbreviated variant in 03d, because UpSet set labels have more room).
# `case_when` clause order encodes priority when `class_max` mentions multiple
# tissues; `Multi` catches anything unclassified.
bodymap_tissue_for_cluster <- function(cluster_num) {
  info <- sb_som_info[cluster_num, ]
  if (!is.null(info$constitutive_class) && info$constitutive_class == "TRUE")
    return("Constitutive")
  cm <- info$class_max
  case_when(
    grepl("Brain", cm)      ~ "Brain",
    grepl("Muscle", cm)     ~ "Muscle",
    grepl("Liver", cm)      ~ "Liver",
    grepl("Testes", cm)     ~ "Testes",
    grepl("Ova", cm)        ~ "Ovary",
    grepl("Gill", cm)       ~ "Gill",
    grepl("HeadKidney", cm) ~ "Head_kidney",
    grepl("Intestine", cm)  ~ "Intestine",
    TRUE                    ~ "Multi"
  )
}

bm_tissue_labels <- sapply(1:36, bodymap_tissue_for_cluster)
names(bm_tissue_labels) <- as.character(1:36)

bm_tissue_order <- c("Brain", "Muscle", "Gill", "Head_kidney",
                      "Intestine", "Liver", "Testes", "Ovary",
                      "Multi", "Constitutive")

tissue_cols <- c(
  "Brain" = "#dce648ff", "Muscle" = "salmon", "Liver" = "#8a0000ff",
  "Testes" = "forestgreen", "Ovary" = "#ffa300ff", "Gill" = "red2",
  "Head_kidney" = "black", "Intestine" = "hotpink",
  "Multi" = "skyblue", "Constitutive" = "#becacaff"
)

bm_constitutive <- which(sapply(1:36, function(i)
  !is.null(sb_som_info[i,]$constitutive_class) && sb_som_info[i,]$constitutive_class == "TRUE"))

for (redip in c("AORe", "LORe")) {
  detail_sub <- bodymap_result$detail %>% filter(proxiPhylogeny == redip)
  lbl <- ifelse(redip == "AORe", "Early", "Late")

  make_tissue_upset(detail_sub, bm_tissue_labels, bm_tissue_order, tissue_cols,
    file.path(outdir, paste0("C1_bodymap_upset_", tolower(lbl))))

  nc_detail <- detail_sub %>%
    filter(!cluster1 %in% bm_constitutive, !cluster2 %in% bm_constitutive)
  nc_tissue_order <- bm_tissue_order[bm_tissue_order != "Constitutive"]
  nc_tissue_cols <- tissue_cols[nc_tissue_order]

  make_tissue_upset(nc_detail, bm_tissue_labels, nc_tissue_order, nc_tissue_cols,
    file.path(outdir, paste0("C1_bodymap_upset_", tolower(lbl), "_noconst")))
}

cat("\nDone.\n")
