#!/usr/bin/env Rscript
# =============================================================================
# 03g_lore_ratio_panel.R
# -----------------------------------------------------------------------------
# Purpose
#   Per-cluster LORe% bar panels for the C1 ohnolog SOM analysis (R1-C6).
#   Replaces the busy 4-category stacked composition bars (03c) as the
#   primary visualisation of the question "are Early and Late ohnologs
#   distributed unevenly across SOM clusters?". Each bar shows the
#   percentage of ohnolog genes in a cluster that belong to the Late
#   (LORe) sub-class, with a horizontal dashed line marking the
#   genome-wide LORe fraction (~12% in both maps) and significance
#   markers from the per-cluster binomial test (BH-adjusted): ▲ above
#   bars significantly enriched in LORe, ▼ above bars significantly
#   depleted, plus a *, **, *** tier from padj.
#
# Inputs
#   <data_path>/c1_extended_results.RData   (generated by 03b)
#     Uses devmap_gene_counts, bodymap_gene_counts (per-cluster AORe/LORe
#     counts) and devmap_ratio_tests, bodymap_ratio_tests (per-cluster
#     binomial tests, baseline LORe fraction in $p_lore).
#
# Outputs → <outdir>/panels/{pdf|png}/{devmap|bodymap}/{const|noconst}/
#   C1_devmap_lore_proportion[.noconst].{pdf,png}
#   C1_bodymap_lore_proportion[.noconst].{pdf,png}
# =============================================================================

suppressPackageStartupMessages({
  library(tidyverse)
  library(viridis)
})

font_family <- "Helvetica"
theme_set(theme_bw(base_size = 11, base_family = font_family))
update_geom_defaults("text",  list(family = font_family))
update_geom_defaults("label", list(family = font_family))

outdir    <- "results/ohnolog/panels"
data_path <- "results/ohnolog/data"

load(file.path(data_path, "c1_extended_results.RData"))

# --- Palettes (mirrored from 03c) -------------------------------------------
inferno_cols     <- rev(inferno(12, begin = 0.15, end = 0.9))
constitutive_col <- "#becacaff"
final_colors_ssal <- c(inferno_cols, rep(constitutive_col, 4))
desired_order      <- c(13, 10, 15, 14, 16, 12, 4, 2, 1, 6, 9, 5, 3, 8, 11, 7)
color_order_for_objects <- match(1:16, desired_order)
ordered_palette_salmon_devmap <- final_colors_ssal[color_order_for_objects]
devmap_palette <- setNames(ordered_palette_salmon_devmap, as.character(1:16))

devmap_label_map <- c(
  "13"="M1","10"="M2","15"="M3","14"="M4",
  "16"="B1","12"="B2","4"="G1","2"="S1","1"="S2",
  "6"="P1","5"="P2",
  "7"="C1","11"="C2","8"="C3","3"="C4"
)

devmap_cluster_order_heatmap <- c(13, 10, 15, 14, 16, 12, 4, 2, 1, 6, 5)
devmap_constitutive <- c(7, 11, 8, 3)
full_devmap_order   <- c(devmap_cluster_order_heatmap, devmap_constitutive)

tissue_cols <- c(
  "Brain"="#dce648ff", "Muscle"="salmon", "Liver"="#8a0000ff",
  "Testes"="forestgreen", "Ovary"="#ffa300ff", "Gill"="red2",
  "Head kidney"="black", "Intestine"="hotpink",
  "Multi"="skyblue", "Constitutive"="#becacaff"
)

# Collapse a verbose SOM/cluster label to a short tissue name (e.g. "Brain").
simplify_tissue <- function(lbl) {
  case_when(
    grepl("Brain", lbl)        ~ "Brain",
    grepl("Muscle", lbl)       ~ "Muscle",
    grepl("Liver", lbl)        ~ "Liver",
    grepl("Testes", lbl)       ~ "Testes",
    grepl("Ova", lbl)          ~ "Ovary",
    grepl("Gill", lbl)         ~ "Gill",
    grepl("HeadKidney", lbl)   ~ "Head kidney",
    grepl("Intestine", lbl)    ~ "Intestine",
    grepl("Constitutive", lbl) ~ "Constitutive",
    TRUE                        ~ "Multi"
  )
}

tissue_order <- c("Brain","Muscle","Gill","Head kidney",
                   "Intestine","Liver","Testes","Ovary","Constitutive")

# --- save helper (mirrors 03c) ----------------------------------------------
save_gg <- function(fname_base, p, w, h, dpi = 300) {
  name    <- basename(fname_base)
  map     <- if (grepl("_bodymap_", name)) "bodymap" else "devmap"
  variant <- if (grepl("_noconst$", name)) "noconst" else "const"
  pdf_dir <- file.path(outdir, "pdf", map, variant)
  png_dir <- file.path(outdir, "png", map, variant)
  dir.create(pdf_dir, showWarnings = FALSE, recursive = TRUE)
  dir.create(png_dir, showWarnings = FALSE, recursive = TRUE)
  ggsave(file.path(pdf_dir, paste0(name, ".pdf")), p, width = w, height = h,
         device = cairo_pdf)
  ggsave(file.path(png_dir, paste0(name, ".png")), p, width = w, height = h, dpi = dpi)
  cat("  Saved", name, "→", map, "/", variant, "\n")
}

# =============================================================================
# DEVMAP
# -----------------------------------------------------------------------------
# Per-cluster LORe% with a horizontal baseline at the genome-wide LORe
# fraction (devmap_ratio_tests$p_lore). Marker construction:
#   marker_glyph = ▲ for significantly enriched (sig != "" & enrichment=="up"),
#                  ▼ for significantly depleted, "" otherwise.
#   We render the glyph and the asterisk-tier (sig) above the bar so the
#   reader sees both direction and strength at a glance.
# =============================================================================

devmap_p_lore <- devmap_ratio_tests$p_lore * 100   # baseline as %

devmap_df <- devmap_gene_counts %>%
  filter(cluster != 9) %>%                          # drop P*
  left_join(devmap_ratio_tests$tests %>%
              select(cluster, padj, sig, enrichment),
            by = "cluster") %>%
  mutate(
    label_ms = devmap_label_map[as.character(cluster)],
    label_ms = factor(label_ms,
      levels = devmap_label_map[as.character(full_devmap_order)]),
    marker = case_when(
      is.na(sig) | sig == ""        ~ "",
      enrichment == "up"            ~ paste0("▲", sig),  # ▲ + stars
      enrichment == "down"          ~ paste0("▼", sig),  # ▼ + stars
      TRUE                           ~ ""
    )
  )

# Build the DevMap per-cluster LORe-fraction panel.
devmap_lore_plot <- function(df) {
  ggplot(df, aes(x = label_ms, y = pct_LORe, fill = as.character(cluster))) +
    geom_col(colour = "grey20", linewidth = 0.3, width = 0.75) +
    geom_hline(yintercept = devmap_p_lore, linetype = "dashed",
               colour = "grey30", linewidth = 0.6) +
    annotate("text", x = Inf, y = devmap_p_lore,
             label = sprintf("genome-wide %.1f%%", devmap_p_lore),
             hjust = 1.05, vjust = -0.4, size = 3.2,
             family = font_family, colour = "grey30") +
    geom_text(aes(label = marker, y = pct_LORe + 0.6),
              vjust = 0, size = 3.8, fontface = "bold",
              family = font_family,
              colour = "grey15") +
    scale_fill_manual(values = devmap_palette, guide = "none") +
    scale_y_continuous(expand = expansion(mult = c(0, 0.12))) +
    labs(x = "DevMap SOM cluster",
         y = "LORe (Late) ohnologs (%)") +
    theme(
      panel.grid.major.x = element_blank(),
      axis.text.x        = element_text(face = "bold")
    )
}

p_dev_const   <- devmap_lore_plot(devmap_df)
p_dev_noconst <- devmap_lore_plot(devmap_df %>% filter(label != "Constitutive"))

save_gg(file.path(outdir, "C1_devmap_lore_proportion"),         p_dev_const,   7.5, 4)
save_gg(file.path(outdir, "C1_devmap_lore_proportion_noconst"), p_dev_noconst, 6.5, 4)

# =============================================================================
# BODYMAP
# -----------------------------------------------------------------------------
# Same template, faceted by dominant tissue. The tissue key comes from
# `simplify_tissue()` applied to the gene_counts label; cluster x-axis
# ordering follows tissue then cluster ID. Constitutive clusters drop in
# the _noconst variant.
# =============================================================================

bodymap_p_lore <- bodymap_ratio_tests$p_lore * 100

bodymap_df <- bodymap_gene_counts %>%
  left_join(bodymap_ratio_tests$tests %>%
              select(cluster, padj, sig, enrichment),
            by = "cluster") %>%
  mutate(
    tissue = simplify_tissue(label),
    tissue = factor(tissue, levels = tissue_order),
    marker = case_when(
      is.na(sig) | sig == ""        ~ "",
      enrichment == "up"            ~ paste0("▲", sig),
      enrichment == "down"          ~ paste0("▼", sig),
      TRUE                           ~ ""
    )
  )

# Build the BodyMap per-cluster LORe-fraction panel (tissue-faceted).
bodymap_lore_plot <- function(df) {
  df <- df %>% arrange(tissue, cluster)
  df$cluster <- factor(df$cluster, levels = unique(df$cluster))
  ggplot(df, aes(x = cluster, y = pct_LORe, fill = tissue)) +
    geom_col(colour = "grey20", linewidth = 0.3, width = 0.8) +
    geom_hline(yintercept = bodymap_p_lore, linetype = "dashed",
               colour = "grey30", linewidth = 0.6) +
    geom_text(aes(label = marker, y = pct_LORe + 0.6),
              vjust = 0, size = 3.8, fontface = "bold",
              family = font_family, colour = "grey15") +
    scale_fill_manual(values = tissue_cols, name = "Tissue") +
    scale_y_continuous(expand = expansion(mult = c(0, 0.12))) +
    facet_grid(. ~ tissue, scales = "free_x", space = "free_x") +
    labs(x = "BodyMap SOM cluster",
         y = "LORe (Late) ohnologs (%)") +
    theme(
      panel.grid.major.x = element_blank(),
      strip.background   = element_rect(fill = "grey92", colour = NA),
      strip.text         = element_text(face = "bold", size = 9),
      legend.position    = "none",
      axis.text.x        = element_text(size = 9)
    )
}

p_body_const   <- bodymap_lore_plot(bodymap_df)
p_body_noconst <- bodymap_lore_plot(bodymap_df %>% filter(tissue != "Constitutive"))

save_gg(file.path(outdir, "C1_bodymap_lore_proportion"),         p_body_const,   12, 4)
save_gg(file.path(outdir, "C1_bodymap_lore_proportion_noconst"), p_body_noconst, 11, 4)

cat("\nDone.\n")
