#!/usr/bin/env Rscript
# =============================================================================
# 03g_early_late_ratio_panel.R
# -----------------------------------------------------------------------------
# Purpose
#   Per-cluster Early-to-Late gene ratio panels for the C1 ohnolog SOM
#   analysis (R1-C6). Bar height = AORe/LORe ratio per cluster (with
#   Haldane–Anscombe +0.5 correction). Bars are filled with a visually
#   stacked AORe/LORe percentage breakdown drawn as two geom_rect layers,
#   each labelled in-bar with the cluster's AORe% / LORe%. 95% CI on the
#   log-ratio is overlaid as error bars. The dashed horizontal line marks
#   the genome-wide Early/Late ratio computed from the singleton-inclusive
#   composition pool. ▲ / ▼ + asterisks above each bar mark per-cluster
#   deviations from the genome-wide ratio (binomial test, BH-adjusted).
#
#   Companion panel: per-cluster co-clustering rate ratio (LORe rate /
#   AORe rate) with 95% CI on the log-RR. Min-n gated.
#
# Inputs
#   <data_path>/c1_extended_results.RData   (generated by 03b)
#     devmap_gene_counts, bodymap_gene_counts          (composition table
#                                                       with el_ratio + CI)
#     devmap_ratio_tests, bodymap_ratio_tests          (per-cluster binomial
#                                                       vs genome-wide ratio)
#     devmap_coclust_ratio_tests, bodymap_coclust_ratio_tests
#                                                      (per-cluster log-RR
#                                                       on co-clustering)
# =============================================================================

suppressPackageStartupMessages({
  library(tidyverse)
  library(viridis)
})

font_family <- "Helvetica"
theme_set(theme_bw(base_size = 11, base_family = font_family))
update_geom_defaults("text",  list(family = font_family))
update_geom_defaults("label", list(family = font_family))

outdir    <- "results/ohnolog/panels"
data_path <- "results/ohnolog/data"

load(file.path(data_path, "c1_extended_results.RData"))

# --- Palettes (mirrored from 03c) -------------------------------------------
inferno_cols     <- rev(inferno(12, begin = 0.15, end = 0.9))
constitutive_col <- "#becacaff"
final_colors_ssal <- c(inferno_cols, rep(constitutive_col, 4))
desired_order      <- c(13, 10, 15, 14, 16, 12, 4, 2, 1, 6, 9, 5, 3, 8, 11, 7)
color_order_for_objects <- match(1:16, desired_order)
ordered_palette_salmon_devmap <- final_colors_ssal[color_order_for_objects]
devmap_palette <- setNames(ordered_palette_salmon_devmap, as.character(1:16))

devmap_label_map <- c(
  "13"="M1","10"="M2","15"="M3","14"="M4",
  "16"="B1","12"="B2","4"="G1","2"="S1","1"="S2",
  "6"="P1","5"="P2",
  "7"="C1","11"="C2","8"="C3","3"="C4"
)

devmap_cluster_order_heatmap <- c(13, 10, 15, 14, 16, 12, 4, 2, 1, 6, 5)
devmap_constitutive <- c(7, 11, 8, 3)
full_devmap_order   <- c(devmap_cluster_order_heatmap, devmap_constitutive)

tissue_cols <- c(
  "Brain"="#dce648ff", "Muscle"="salmon", "Liver"="#8a0000ff",
  "Testes"="forestgreen", "Ovary"="#ffa300ff", "Gill"="red2",
  "Head kidney"="black", "Intestine"="hotpink",
  "Multi"="skyblue", "Constitutive"="#becacaff"
)

aore_col <- "#b2182b"   # AORe / Early — red
lore_col <- "#2166ac"   # LORe / Late  — blue

simplify_tissue <- function(lbl) {
  case_when(
    grepl("Brain", lbl)        ~ "Brain",
    grepl("Muscle", lbl)       ~ "Muscle",
    grepl("Liver", lbl)        ~ "Liver",
    grepl("Testes", lbl)       ~ "Testes",
    grepl("Ova", lbl)          ~ "Ovary",
    grepl("Gill", lbl)         ~ "Gill",
    grepl("HeadKidney", lbl)   ~ "Head kidney",
    grepl("Intestine", lbl)    ~ "Intestine",
    grepl("Constitutive", lbl) ~ "Constitutive",
    TRUE                        ~ "Multi"
  )
}

tissue_order <- c("Brain","Muscle","Gill","Head kidney",
                   "Intestine","Liver","Testes","Ovary","Constitutive")

# BodyMap multi-tissue clusters: stage_specific == FALSE & constitutive == FALSE
# in sb_som_info. These keep their highest-expression-tissue facet position
# (so no ohnolog gene copies are dropped) but are coloured as "Multi" so the
# reader can tell them apart from genuinely tissue-specific clusters. List is
# read from the deposited data/ohnolog/bodymap_cluster_map.tsv.
bodymap_cluster_map <- readr::read_tsv(
  "data/ohnolog/bodymap_cluster_map.tsv", show_col_types = FALSE)
bodymap_multi_clusters <- bodymap_cluster_map$class_number[
  bodymap_cluster_map$category == "Multi"]
# Diego's curated 1-36 numbering used in S25 (1-20 = tissue-specific,
# 21-31 = multi-tissue grouped by peak tissue, 32-36 = constitutive). Used
# as the x-axis labels for BodyMap A(i) so this panel matches S25 / S26.
bodymap_display_id <- setNames(bodymap_cluster_map$display_id,
                               as.character(bodymap_cluster_map$class_number))

# Manuscript-pack mirror: for the `const` panels that are spliced into the R1
# revision figure pack, write a second copy under manuscript_R1_panels/ with
# the canonical Fig_S{YY,ZZ}_* filename. Keep this table in sync with the
# README in manuscript_R1_panels/. `noconst` variants are not mirrored.
manuscript_pack_dir <- "results/ohnolog/panels"
manuscript_pack_map <- c(
  C1_devmap_early_late_ratio  = "Fig_SYY_A2_DevMap_early_late_ratio_per_cluster",
  C1_bodymap_early_late_ratio = "Fig_SZZ_A2_BodyMap_early_late_ratio_per_cluster"
)

save_gg <- function(fname_base, p, w, h, dpi = 300) {
  name    <- basename(fname_base)
  map     <- if (grepl("_bodymap_", name)) "bodymap" else "devmap"
  variant <- if (grepl("_noconst$", name)) "noconst" else "const"
  pdf_dir <- file.path(outdir, "pdf", map, variant)
  png_dir <- file.path(outdir, "png", map, variant)
  dir.create(pdf_dir, showWarnings = FALSE, recursive = TRUE)
  dir.create(png_dir, showWarnings = FALSE, recursive = TRUE)
  ggsave(file.path(pdf_dir, paste0(name, ".pdf")), p, width = w, height = h,
         device = cairo_pdf)
  ggsave(file.path(png_dir, paste0(name, ".png")), p, width = w, height = h, dpi = dpi)
  cat("  Saved", name, "->", map, "/", variant, "\n")
  if (name %in% names(manuscript_pack_map)) {
    pack_name <- manuscript_pack_map[[name]]
    ggsave(file.path(manuscript_pack_dir, paste0(pack_name, ".pdf")),
           p, width = w, height = h, device = cairo_pdf)
    ggsave(file.path(manuscript_pack_dir, paste0(pack_name, ".png")),
           p, width = w, height = h, dpi = dpi)
    cat("  Mirrored -> manuscript_R1_panels/", pack_name, "\n", sep = "")
  }
}

# Build a long-format frame with one row per (cluster, segment) where each
# segment is the height contribution of AORe vs LORe to the bar (bar total
# height = el_ratio). geom_col(position="stack") then handles facet x-axes
# correctly. Within a bar AORe sits at the bottom, LORe sits on top, in
# proportion to the cluster's composition.
#
# Segment heights:  seg_AORe = el_ratio * pct_AORe/100,  seg_LORe = ratio - seg_AORe
# Label y-positions:  AORe -> seg_AORe / 2     (centre of AORe segment)
#                     LORe -> seg_AORe + (el_ratio - seg_AORe) / 2
to_stacked_long <- function(df) {
  base_cols <- intersect(c("cluster", "label", "AORe", "LORe", "total",
                           "pct_AORe", "pct_LORe", "el_ratio",
                           "ratio_lo", "ratio_hi", "label_ms", "tissue",
                           "marker"), colnames(df))
  df %>%
    select(all_of(base_cols)) %>%
    mutate(seg_AORe = el_ratio * pct_AORe / 100,
           seg_LORe = el_ratio - seg_AORe,
           label_y_AORe = seg_AORe / 2,
           label_y_LORe = seg_AORe + seg_LORe / 2) %>%
    pivot_longer(cols = c(seg_AORe, seg_LORe),
                 names_to  = "segment_name",
                 values_to = "seg_height") %>%
    # Levels ordered so AORe stacks at the bottom, LORe at the top with
    # position_stack(reverse = TRUE) in the geom layer.
    mutate(segment = factor(sub("seg_", "", segment_name),
                            levels = c("AORe", "LORe")),
           pct_lab = ifelse(segment == "AORe",
                            sprintf("%.0f%%", pct_AORe),
                            sprintf("%.0f%%", pct_LORe)),
           seg_label_y = ifelse(segment == "AORe",
                                label_y_AORe, label_y_LORe))
}

# =============================================================================
# DEVMAP: composition ratio panel (A(ii))
# =============================================================================

devmap_genome_ratio <- with(devmap_gene_counts,
                            (sum(AORe) + 0.5) / (sum(LORe) + 0.5))

devmap_df <- devmap_gene_counts %>%
  filter(cluster != 9) %>%                          # drop P*
  left_join(devmap_ratio_tests$tests %>%
              select(cluster, padj, sig, enrichment),
            by = "cluster") %>%
  mutate(
    label_ms = devmap_label_map[as.character(cluster)],
    label_ms = factor(label_ms,
      levels = devmap_label_map[as.character(full_devmap_order)]),
    # `enrichment` from build_ratio_tests is keyed on LORe fraction. In the
    # Early-to-Late ratio panel we want ▲ = Early-enriched (bar taller than
    # genome-wide), which is the *opposite* of LORe-enriched, so flip the
    # mapping here.
    marker = case_when(
      is.na(sig) | sig == ""        ~ "",
      enrichment == "up"            ~ paste0("▼", sig),  # LORe-enriched -> Early-depleted
      enrichment == "down"          ~ paste0("▲", sig),  # LORe-depleted -> Early-enriched
      TRUE                           ~ ""
    )
  )

devmap_ratio_plot <- function(df) {
  ymax <- max(df$el_ratio, na.rm = TRUE) * 1.15
  ggplot(df, aes(x = label_ms, y = el_ratio,
                 fill = as.character(cluster))) +
    geom_col(colour = "grey20", linewidth = 0.3, width = 0.75) +
    geom_hline(yintercept = devmap_genome_ratio, linetype = "dashed",
               colour = "grey30", linewidth = 0.6) +
    annotate("text", x = Inf, y = devmap_genome_ratio,
             label = sprintf("genome-wide %.2f", devmap_genome_ratio),
             hjust = 1.05, vjust = -0.4, size = 3.2,
             family = font_family, colour = "grey30") +
    geom_text(aes(label = marker, y = el_ratio + ymax * 0.02),
              vjust = 0, size = 3.6, fontface = "bold",
              family = font_family, colour = "grey15") +
    scale_fill_manual(values = devmap_palette, guide = "none") +
    scale_y_continuous(expand = expansion(mult = c(0, 0.18))) +
    labs(x = "DevMap SOM cluster",
         y = "Early-to-Late gene ratio (AORe / LORe)") +
    theme(
      panel.grid.major.x = element_blank(),
      axis.text.x        = element_text(face = "bold")
    )
}

p_dev_const   <- devmap_ratio_plot(devmap_df)
p_dev_noconst <- devmap_ratio_plot(devmap_df %>% filter(label != "Constitutive"))

save_gg(file.path(outdir, "C1_devmap_early_late_ratio"),         p_dev_const,   7.5, 4)
save_gg(file.path(outdir, "C1_devmap_early_late_ratio_noconst"), p_dev_noconst, 6.5, 4)

# =============================================================================
# BODYMAP: composition ratio panel (A(ii))
# =============================================================================

bodymap_genome_ratio <- with(bodymap_gene_counts,
                             (sum(AORe) + 0.5) / (sum(LORe) + 0.5))

bodymap_df <- bodymap_gene_counts %>%
  left_join(bodymap_ratio_tests$tests %>%
              select(cluster, padj, sig, enrichment),
            by = "cluster") %>%
  mutate(
    tissue = simplify_tissue(label),
    tissue = factor(tissue, levels = tissue_order),
    # Curated 1-36 display id (matches S25 / S26). Used as x-axis tick label.
    display_id = bodymap_display_id[as.character(cluster)],
    # Fill key: identical to `tissue` except the 11 multi-tissue clusters are
    # recoloured "Multi". Facet position and ordering still use `tissue`, so
    # multi clusters stay exactly where they are — only the bar colour changes.
    fill_cat = ifelse(cluster %in% bodymap_multi_clusters,
                      "Multi", as.character(tissue)),
    # `enrichment` from build_ratio_tests is keyed on LORe fraction. In the
    # Early-to-Late ratio panel we want ▲ = Early-enriched (bar taller than
    # genome-wide), which is the *opposite* of LORe-enriched, so flip the
    # mapping here.
    marker = case_when(
      is.na(sig) | sig == ""        ~ "",
      enrichment == "up"            ~ paste0("▼", sig),  # LORe-enriched -> Early-depleted
      enrichment == "down"          ~ paste0("▲", sig),  # LORe-depleted -> Early-enriched
      TRUE                           ~ ""
    )
  )

# Final figure-pack target: inner panel rectangle = 252.98 pt x 114.75 pt
# (3.514 x 1.594 in). Diego scales/aligns in Illustrator after export, so we
# ship at a slightly larger canvas with axes + labels and set every text element
# to 6 pt Helvetica regular black (minimum legible size at the final scale).
# x-axis cluster numbers rotated 45 deg so two-digit display ids don't crowd
# the narrow facets. No tissue strip text — tissue is communicated by bar fill
# (Diego adds tissue annotations in Illustrator).
font_family <- "Helvetica"
text_pt <- 6   # final-size minimum (pt). geom_text() takes mm: 6 pt = 2.117 mm.
text_mm <- text_pt / .pt   # ggplot2's .pt = 72.27/25.4

bodymap_ratio_plot <- function(df) {
  # Sort within each tissue facet by display_id so labels run ascending
  # (e.g. Brain facet -> 1,2,3,4,5,21,22). Tissue-specific bars (display_id
  # <= 20) precede Multi bars (>=21) within each facet by construction.
  df <- df %>% arrange(tissue, display_id)
  df$display_f <- factor(df$display_id, levels = unique(df$display_id))
  ymax <- max(df$el_ratio, na.rm = TRUE) * 1.15
  ggplot(df, aes(x = display_f, y = el_ratio, fill = fill_cat)) +
    geom_col(colour = "black", linewidth = 0.25, width = 0.8) +
    geom_hline(yintercept = bodymap_genome_ratio, linetype = "dashed",
               colour = "black", linewidth = 0.4) +
    geom_text(aes(label = marker, y = el_ratio + ymax * 0.02),
              vjust = 0, size = text_mm, family = font_family,
              colour = "black") +
    scale_fill_manual(values = tissue_cols, name = "Tissue") +
    scale_y_continuous(expand = expansion(mult = c(0, 0.18))) +
    facet_grid(. ~ tissue, scales = "free_x", space = "free_x") +
    labs(x = NULL,
         y = "Early-to-Late gene ratio") +
    theme_bw(base_size = text_pt, base_family = font_family) +
    theme(
      text               = element_text(colour = "black", family = font_family),
      axis.text          = element_text(colour = "black", size = text_pt),
      axis.text.x        = element_text(angle = 45, hjust = 1, vjust = 1,
                                        size = text_pt, colour = "black"),
      axis.title         = element_text(colour = "black", size = text_pt),
      axis.ticks         = element_line(colour = "black", linewidth = 0.3),
      # Each tissue facet kept boxed in via panel.border; strip label sits on
      # top, tilted 45 deg, with no grey background box behind the text.
      panel.border       = element_rect(colour = "black", fill = NA,
                                        linewidth = 0.3),
      strip.background   = element_blank(),
      strip.text.x       = element_text(angle = 45, hjust = 0, vjust = 0,
                                        size = text_pt, colour = "black",
                                        margin = margin(0, 0, 1, 0, "pt")),
      strip.placement    = "outside",
      strip.clip         = "off",
      panel.grid         = element_blank(),
      panel.spacing.x    = unit(2, "pt"),
      legend.position    = "none",
      plot.margin        = margin(20, 14, 2, 2, "pt")
    )
}

p_body_const   <- bodymap_ratio_plot(bodymap_df)
p_body_noconst <- bodymap_ratio_plot(bodymap_df %>% filter(tissue != "Constitutive"))

# Canvas sized so the inner panel area lands close to 252.98 x 114.75 pt
# (~3.514 x 1.594 in) at final scale; the extra width/height holds the y-axis
# label/ticks and the 45-deg x-axis tick labels. Diego trims/aligns in
# Illustrator. Constitutive variant slightly narrower (one fewer facet).
save_gg(file.path(outdir, "C1_bodymap_early_late_ratio"),         p_body_const,   4.4, 2.6)
save_gg(file.path(outdir, "C1_bodymap_early_late_ratio_noconst"), p_body_noconst, 4.0, 2.6)

# =============================================================================
# Per-cluster co-clustering RATE ratio (A1 alternate panel)
# Late/Early co-clustering rate per cluster, with 95% CI on the log-RR.
# Clusters failing the min-n gate are greyed out and shown without CI bars.
# =============================================================================

build_coclust_ratio_df <- function(tbl, label_lookup) {
  tbl %>%
    mutate(
      marker = ifelse(!is.na(sig_fisher) & sig_fisher != "" & pass_n,
                      sig_fisher, ""),
      rr_plot    = ifelse(pass_n, rr,    NA_real_),
      rr_lo_plot = ifelse(pass_n, rr_lo, NA_real_),
      rr_hi_plot = ifelse(pass_n, rr_hi, NA_real_)
    )
}

# DevMap co-clustering ratio panel
devmap_cc <- build_coclust_ratio_df(devmap_coclust_ratio_tests$tests) %>%
  filter(cluster != 9) %>%
  mutate(
    label_ms = devmap_label_map[as.character(cluster)],
    label_ms = factor(label_ms,
      levels = devmap_label_map[as.character(full_devmap_order)])
  )

devmap_cc_plot <- function(df) {
  ymax <- max(c(df$rr_hi_plot, df$rr), na.rm = TRUE)
  ggplot(df, aes(x = label_ms, y = rr)) +
    geom_col(aes(fill = pass_n), colour = "grey20", linewidth = 0.3, width = 0.7) +
    geom_errorbar(aes(ymin = rr_lo_plot, ymax = rr_hi_plot),
                  width = 0.2, colour = "grey15", linewidth = 0.4,
                  na.rm = TRUE) +
    geom_hline(yintercept = 1, linetype = "dashed",
               colour = "grey30", linewidth = 0.6) +
    geom_text(aes(y = pmax(rr_hi_plot, rr, na.rm = TRUE) + ymax * 0.04,
                  label = marker),
              vjust = 0, size = 3.6, fontface = "bold",
              family = font_family, colour = "grey15", na.rm = TRUE) +
    scale_fill_manual(values = c("TRUE" = "grey35", "FALSE" = "grey80"),
                      guide = "none") +
    scale_y_continuous(expand = expansion(mult = c(0, 0.18))) +
    labs(x = "DevMap SOM cluster",
         y = "Co-clustering ratio (Early / Late)") +
    theme(
      panel.grid.major.x = element_blank(),
      axis.text.x        = element_text(face = "bold")
    )
}

p_dev_cc <- devmap_cc_plot(devmap_cc)
save_gg(file.path(outdir, "C1_devmap_coclustering_ratio_per_cluster"),
        p_dev_cc, 7.5, 4)

# BodyMap co-clustering ratio panel
bodymap_cc <- build_coclust_ratio_df(bodymap_coclust_ratio_tests$tests) %>%
  mutate(tissue = simplify_tissue(label),
         tissue = factor(tissue, levels = tissue_order))

bodymap_cc_plot <- function(df) {
  df <- df %>% arrange(tissue, cluster)
  df$cluster_f <- factor(df$cluster, levels = unique(df$cluster))
  ymax <- max(c(df$rr_hi_plot, df$rr), na.rm = TRUE)
  ggplot(df, aes(x = cluster_f, y = rr)) +
    geom_col(aes(fill = pass_n), colour = "grey20", linewidth = 0.3, width = 0.7) +
    geom_errorbar(aes(ymin = rr_lo_plot, ymax = rr_hi_plot),
                  width = 0.2, colour = "grey15", linewidth = 0.4,
                  na.rm = TRUE) +
    geom_hline(yintercept = 1, linetype = "dashed",
               colour = "grey30", linewidth = 0.6) +
    geom_text(aes(y = pmax(rr_hi_plot, rr, na.rm = TRUE) + ymax * 0.04,
                  label = marker),
              vjust = 0, size = 3.4, fontface = "bold",
              family = font_family, colour = "grey15", na.rm = TRUE) +
    scale_fill_manual(values = c("TRUE" = "grey35", "FALSE" = "grey80"),
                      guide = "none") +
    scale_y_continuous(expand = expansion(mult = c(0, 0.18))) +
    facet_grid(. ~ tissue, scales = "free_x", space = "free_x") +
    labs(x = "BodyMap SOM cluster",
         y = "Co-clustering ratio (Early / Late)") +
    theme(
      panel.grid.major.x = element_blank(),
      strip.background   = element_rect(fill = "grey92", colour = NA),
      strip.text         = element_text(face = "bold", size = 9),
      axis.text.x        = element_text(size = 9)
    )
}

p_body_cc <- bodymap_cc_plot(bodymap_cc)
save_gg(file.path(outdir, "C1_bodymap_coclustering_ratio_per_cluster"),
        p_body_cc, 12, 4)

cat("\nDone.\n")
