---
title: "Clustering_and_Visualization_Fig2"
author: Diego Perojil Morata
date: "Timestamp: `r format(Sys.time())`"
output:
  html_document:
    df_print: paged
    toc: yes
    number_sections: true
---
```{r}
library(kohonen)
library(uwot)
library(ComplexHeatmap)
library(circlize)
library(viridis)
library(ggplot2)
library(tidyverse)
library(gridExtra)
```

```{r}
source("functions/clustering_and_visualization_functions.R")
```

# Full heatmap visualization
```{r}
sd_heatmap <- make_heatmap(sd_norm,sd_som,sd_som_info$class_number)
td_heatmap <- make_heatmap(td_norm,td_som,td_som_info$class_number)
sb_heatmap <- make_heatmap(sb_norm[,indices_order_ssal],sb_som,sb_som_info$class_number)
tb_heatmap <- make_heatmap(tb_norm[,indices_order_omyk],tb_som,tb_som_info$class_number)

pdf("../results/heatmaps.pdf") # change to system specific path
plot(sd_heatmap)
plot(td_heatmap)
plot(sb_heatmap)
plot(tb_heatmap)
dev.off()
```

# Adjust SOM info based on heatmap
```{r}
sd_som_info <- sd_som_info[c(1:9,11,12,10,13:16),]
td_som_info <- td_som_info[c(1:8,11,10,9,12:16),]

sb_som_info$stage_specific[10] <- "FALSE"
sb_som_info <- arrange(sb_som_info,constitutive_class,desc(stage_specific),class_max,
                      desc(class_max_mean))

tb_som_info$stage_specific[c(5,4,9)] <- "FALSE"
tb_som_info$stage_specific[c(25,27)] <- "TRUE"
tb_som_info <- arrange(tb_som_info,constitutive_class,desc(stage_specific),class_max,
                      desc(class_max_mean))
```

# Re-plot heatmaps with proper order
```{r}
sd_heatmap <- make_heatmap(sd_norm,sd_som,sd_som_info$class_number)
td_heatmap <- make_heatmap(td_norm,td_som,td_som_info$class_number)
sb_heatmap <- make_heatmap(sb_norm[,indices_order_ssal],sb_som,sb_som_info$class_number)
tb_heatmap <- make_heatmap(tb_norm[,indices_order_omyk],tb_som,tb_som_info$class_number)

pdf("../results/heatmaps.pdf") # change to system specific path
plot(sd_heatmap)
plot(td_heatmap)
plot(sb_heatmap)
plot(tb_heatmap)
dev.off()
```


# UMAP generation
```{r}
# Devmap
sd_umap <- sd_norm %>% uwot::umap(init = "pca")
td_umap <- td_norm %>% uwot::umap(init = "pca")

# Bodymap
sb_umap <- sb_norm %>% uwot::umap(init = "pca")
tb_umap <- tb_norm %>% uwot::umap(init = "pca")
```

# Create Salmon and trout palletes
```{r}
sd_pal <- palette_devmap(12,4,sd_som_info$class_number)
td_pal <- palette_devmap(11,5,td_som_info$class_number)

sb_pal <- palette_bodymap(sb_som_info)
tb_pal <- palette_bodymap(tb_som_info)
```

# Make UMAPS with colours
```{r}
sd_umap_cols <- sd_umap %>% as.data.frame() %>% 
  ggplot(aes(V1, -V2)) + #geom_density_2d() + 
  geom_point(aes(colour = factor(sd_som$som$unit.classif)), 
             alpha = .4, size = .1) +
  scale_color_manual(values = sd_pal) +
  theme_classic() +# guides(colour = guide_legend(override.aes = list(size=10)))
  theme(legend.position = "none",
        axis.line = element_blank(),
        axis.text = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank()) + ylim(c(7,-6)) + xlim(c(-8,9))

td_umap_cols <- td_umap %>% as.data.frame() %>% 
  ggplot(aes(-V1, -V2)) + #geom_density_2d() + 
  geom_point(aes(colour = factor(td_som$som$unit.classif)), 
             alpha = .4, size = .1) + 
  scale_color_manual(values = td_pal) +
  ylim(-7,6) + xlim(8,-8) + 
  theme_classic() +# guides(colour = guide_legend(override.aes = list(size=10)))
  theme(legend.position = "none",
        axis.line = element_blank(),
        axis.text = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank()) + ylim(7,-6)

combined_umaps <- grid.arrange(sd_umap_cols,td_umap_cols,nrow = 1)

sb_umap_cols <- sb_umap %>% as.data.frame() %>% 
  ggplot(aes(V1, -V2)) + #geom_density_2d() + 
  geom_point(aes(colour = factor(sb_som$som$unit.classif,levels = sb_som_info$class_number)), 
             alpha = .4, size = .1) +
  scale_color_manual(values = sb_pal) +
  theme_classic() +# guides(colour = guide_legend(override.aes = list(size=10)))
  theme(legend.position = "none",
        axis.line = element_blank(),
        axis.text = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank()) #+ ylim(c(7,-6)) + xlim(c(-8,9))

tb_umap_cols <- tb_umap %>% as.data.frame() %>% 
  ggplot(aes(-V1, -V2)) + #geom_density_2d() + 
  geom_point(aes(colour = factor(tb_som$som$unit.classif,levels = tb_som_info$class_number)), 
             alpha = .4, size = .1) +
  scale_color_manual(values = tb_pal) +
  theme_classic() +# guides(colour = guide_legend(override.aes = list(size=10)))
  theme(legend.position = "none",
        axis.line = element_blank(),
        axis.text = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank()) #+ ylim(c(7,-6)) + xlim(c(-8,9))
```

# Plot stage specific only heatmaps
```{r}
sd_heatmap_specific <- make_heatmap(sd_norm[which(sd_som$som$unit.classif %in% sd_som_info$class_number[c(1:9,11,12)]),],sd_som,sd_som_info$class_number[c(1:9,11,12)])
td_heatmap_specific <- make_heatmap(td_norm[which(td_som$som$unit.classif %in% td_som_info$class_number[c(1:8,10,11)]),],td_som,td_som_info$class_number[c(1:8,10,11)])

sd_heatmap_specific_grob <- grid.grabExpr(draw(sd_heatmap_specific))
td_heatmap_specific_grob <- grid.grabExpr(draw(td_heatmap_specific))

specific_heatmaps <- grid.arrange(sd_heatmap_specific_grob,td_heatmap_specific_grob,nrow=1)


sb_heatmap_specific <- make_heatmap(
  sb_norm[which(sb_som$som$unit.classif %in% sb_som_info$class_number[which(sb_som_info$stage_specific == TRUE)]),indices_order_ssal],
  sb_som,
  sb_som_info$class_number[which(sb_som_info$stage_specific == TRUE)]
)

tb_heatmap_specific <- make_heatmap(
  tb_norm[which(tb_som$som$unit.classif %in% tb_som_info$class_number[which(tb_som_info$stage_specific == TRUE)]),indices_order_omyk],
  tb_som,
  tb_som_info$class_number[which(tb_som_info$stage_specific == TRUE)]
)
```

# Combine heatmaps and umaps into one panel
```{r}
dev_rna_panel <- grid.arrange(combined_umaps,specific_heatmaps,ncol = 1,heights = c(1,3))
```

# SOM palette and coloured UMAPS

```{r}
# ssal devmap

stage_specific_cols_ssal <- inferno(12,begin = 0.15, end = 0.9)
constitutive <- c("#becacaff")
final_colors_ssal <- c(stage_specific_cols_ssal, rep(constitutive,4))

desired_order <- c(13,10,15,14,16,12,4,2,1,6,9,5,3,8,11,7)
color_order_for_objects <- match(1:16, desired_order)
ordered_palette_salmon_devmap <- final_colors_ssal[color_order_for_objects]

sd_umap_cols <- sd_umap %>% as.data.frame() %>% 
  ggplot(aes(-V1, -V2)) + #geom_density_2d() + 
  geom_point(aes(colour = factor(sd_som$som$unit.classif)), 
             alpha = .4, size = .8) + 
  scale_color_manual(values = ordered_palette_salmon_devmap) +
  theme_classic() +# guides(colour = guide_legend(override.aes = list(size=10)))
  theme(legend.position = "none") + ylim(c(7,-6)) + xlim(c(-8,9))

# omyk devmap

stage_specific_cols_omyk <- inferno(11,begin = 0.15, end = 0.9)
constitutive <- c("#becacaff")
final_colors_omyk <- c(stage_specific_cols_omyk, rep(constitutive,5))

desired_order_trout <- c(13,14,9,5,1,2,3,8,12,15,16,7,4,11,6,10)
color_order_for_objects <- match(1:16, desired_order_trout)
ordered_palette_trout_devmap <- final_colors_omyk[color_order_for_objects]

td_umap_cols <- td_umap %>% as.data.frame() %>% 
  ggplot(aes(-V1, -V2)) + #geom_density_2d() + 
  geom_point(aes(colour = factor(td_som$som$unit.classif)), 
             alpha = .4, size = 1) + 
  scale_color_manual(values = ordered_palette_trout_devmap) +
  ylim(-7,6) + xlim(8,-8) + 
  theme_classic() +# guides(colour = guide_legend(override.aes = list(size=10)))
  theme(legend.position = "none") + ylim(7,-6)

# To finish...
# salmon bodymap

# trout bodymap
```

```{r}

```


